import { db } from "@/lib/db";
export const reportNames = { rooms: "Occupied and vacant rooms", arrears: "Rent arrears", payments: "Payment history", income: "Semester income", students: "Student register", checkouts: "Checkout records" } as const;
export type ReportType = keyof typeof reportNames;
export async function getReport(type: ReportType, organizationId: string) {
  if (type === "rooms") { const rows = await db.room.findMany({ where: { organizationId }, include: { roomType: true, occupancies: { where: { status: "ACTIVE" }, include: { student: true } } }, orderBy: { number: "asc" } }); return { columns: ["Room", "Type", "Capacity", "Occupants", "Status"], rows: rows.map((r) => [r.number, r.roomType.name, String(r.capacityOverride ?? r.roomType.defaultCapacity), r.occupancies.map((o) => o.student.fullName).join("; ") || "None", r.status]) }; }
  if (type === "arrears") { const rows = await db.charge.findMany({ where: { organizationId, status: { notIn: ["FULLY_PAID", "WAIVED"] } }, include: { student: true, payments: { where: { reversedAt: null } } }, orderBy: { dueDate: "asc" } }); return { columns: ["Student", "Description", "Charge", "Paid", "Balance", "Due date", "Status"], rows: rows.map((c) => { const paid = c.payments.reduce((s,p) => s + Number(p.amount),0); return [c.student.fullName,c.description,String(c.amount),String(paid),String(Math.max(0,Number(c.amount)-paid)),c.dueDate.toISOString().slice(0,10),c.status]; }) }; }
  if (type === "payments") { const rows = await db.payment.findMany({ where: { organizationId }, include: { student: true, charge: true }, orderBy: { paidAt: "desc" } }); return { columns: ["Receipt", "Student", "Amount", "Method", "Reference", "Date", "Charge", "Status", "Reversal reason"], rows: rows.map((p) => [p.receiptNumber,p.student.fullName,String(p.amount),p.method,p.reference ?? "",p.paidAt.toISOString().slice(0,10),p.charge.description,p.reversedAt ? "REVERSED" : "ACTIVE",p.reversalReason ?? ""]) }; }
  if (type === "income") { const rows = await db.semester.findMany({ where: { organizationId }, include: { charges: { include: { payments: { where: { reversedAt: null } } } } }, orderBy: { startDate: "desc" } }); return { columns: ["Semester", "Expected", "Collected", "Outstanding", "Status"], rows: rows.map((s) => { const expected=s.charges.reduce((a,c)=>a+Number(c.amount),0); const paid=s.charges.reduce((a,c)=>a+c.payments.reduce((x,p)=>x+Number(p.amount),0),0); return [s.name,String(expected),String(paid),String(Math.max(0,expected-paid)),s.status]; }) }; }
  if (type === "students") { const rows = await db.student.findMany({ where: { organizationId }, include: { guardian: true, occupancies: { where: { status: "ACTIVE" }, include: { room: true }, take: 1 } }, orderBy: { fullName: "asc" } }); return { columns: ["Student", "Phone", "Admission", "Room", "Guardian", "Guardian phone", "Status"], rows: rows.map((s) => [s.fullName,s.phone,s.admissionNumber ?? "",s.occupancies[0]?.room.number ?? "",s.guardian?.name ?? "",s.guardian?.phone ?? "",s.status]) }; }
  const rows = await db.occupancy.findMany({ where: { organizationId, status: "CHECKED_OUT" }, include: { student: true, room: true, semester: true }, orderBy: { checkedOutAt: "desc" } }); return { columns: ["Student", "Room", "Semester", "Check-in", "Checkout", "Final balance", "Clearance"], rows: rows.map((o) => [o.student.fullName,o.room.number,o.semester.name,o.checkInAt.toISOString().slice(0,10),o.checkedOutAt?.toISOString().slice(0,10) ?? "",String(o.finalBalance),o.clearanceStatus]) };
}
