export type GuideRole = "PUBLIC" | "TENANT" | "CARETAKER" | "MANAGEMENT";
export type GuideTopic = { title: string; terms: string; body: string; href: string; action: string };
export function systemGuide(role: GuideRole): GuideTopic[] {
  const common: GuideTopic[] = [
    { title: "Existing tenant registration", terms: "register registration account signup join student tenant password login", body: "Existing residents open their hostel website, choose Student sign in, then Create my tenant account. Submit the recorded name, phone and current room, and choose a password. Management independently verifies identity and links the request to the existing tenancy. It does not book a room or grant access immediately. If you already have an account, sign in or ask management for recovery.", href: role === "MANAGEMENT" ? "/students/registrations" : "/tenant/register", action: role === "MANAGEMENT" ? "Review registrations" : "Request an account" },
    { title: "WhatsApp and system messages", terms: "whatsapp business send sms delivery message", body: "Private messages in the tenant portal can be read and answered inside the system. WhatsApp currently opens a draft on your device and requires you to press Send. Its replies stay in WhatsApp. Automatic sending and verified delivery are not connected.", href: role === "MANAGEMENT" || role === "CARETAKER" ? "/communications/whatsapp" : "/tenant/contact", action: "Open communication options" },
    { title: "Urgent matters and privacy", terms: "emergency urgent help privacy safe support", body: "For an urgent safety concern, contact your hostel's management or gate team directly. Portal messages are not continuously monitored. Tenants see their own messages and visits; authorized staff see records for their own hostel. Do not share passwords or full identity-document numbers in messages.", href: role === "PUBLIC" ? "/" : role === "TENANT" ? "/tenant/contact" : "/communications/whatsapp", action: "Contact the hostel" },
  ];
  if (role === "TENANT" || role === "PUBLIC") common.push(
    { title: "Message the owner or management", terms: "owner landlord landlady admin management complaint repair question reply conversation", body: "Sign in to your tenant account and open Contact management. Write a subject and message. The owner, administrator or manager can reply in the same private conversation, and can also start a conversation with you. Check My messages and My conversations for updates.", href: "/tenant/contact", action: "Contact management" },
    { title: "Register my visitor", terms: "visitor guest visit arrival leave departure checkout checkin gate security caretaker", body: "Open My visitors, choose your current room and enter the visitor's name, phone, purpose, expected arrival and departure. Times are in the hostel's displayed time zone. The caretaker/security team verifies entry and exit. You may cancel before check-in; you cannot check a visitor in or out yourself. An overdue record means departure has not been recorded.", href: "/tenant/visitors", action: "My visitors" },
    { title: "Rent, receipts and account", terms: "balance rent receipt money payment statement", body: "Your tenant account shows charges, recorded payments, balances and your room. Ask management about missing or incorrect payments; do not send account details to another tenant. The assistant cannot accept payments, change rent or mark a balance paid.", href: "/tenant/account", action: "My account" },
  );
  if (role === "MANAGEMENT" || role === "CARETAKER") common.push(
    { title: "Who has not checked out?", terms: "visitor guest overdue not out checkout departure inside late left alert", body: "Use the live alerts above or Visitor register → Check-out overdue. These are checked-in visitors whose expected departure has passed without a recorded check-out. Verify with the host or gate team, then record the actual departure. Never infer physical presence or automatically close the visit.", href: "/visitors?filter=OVERDUE", action: "Review overdue check-outs" },
    { title: "Verify a visitor at the gate", terms: "visitor security caretaker gate approve verify arrival checkin entry", body: "Open the visitor register and find the expected visitor by name, host or room. Verify identity and the host, confirm arrival at the gate, then select Verify check-in. When the visitor leaves, confirm departure and select Verify check-out. Each action records your staff account and a timestamp. A request alone is not permission to enter.", href: "/visitors", action: "Open visitor register" },
  );
  if (role === "MANAGEMENT") common.push(
    { title: "Start or answer a private conversation", terms: "owner landlord tenant student message reply conversation inbox complaint", body: "Open Student inbox to select an activated current tenant, write a subject and start a private conversation. Tenants reply from Contact management. Open conversations await management. For announcements to all or selected tenants, use Communications.", href: "/communications/inbox", action: "Open student inbox" },
    { title: "Approve an existing resident account", terms: "registration register approve identity self activate pending", body: "Open Tenant registration. Independently verify the requester in person or through the contact already on file, then select the matching resident and activate. Names, phone and current room must match. Existing or blocked accounts cannot be overwritten through self-registration. Requests expire after seven days.", href: "/students/registrations", action: "Verify registrations" },
    { title: "Staff access and system health", terms: "staff permissions role user access health healthfix failure error", body: "Owners and admins create individual staff accounts in Users & Permissions. Assign caretaker access to authorized caretakers or gate staff. HealthFix reports checks and permitted repairs; it does not prove every workflow or external delivery works. Staff must use their own accounts so visitor verifications are attributable.", href: "/users", action: "Users & Permissions" },
  );
  return common;
}
export function searchSystemGuide(topics: GuideTopic[], question: string) {
  const words = question.toLowerCase().slice(0, 300).match(/[a-z]{3,}/g)?.filter(x => !["the", "how", "can", "does", "who", "what", "with", "this", "that", "have", "has", "and", "for", "someone"].includes(x)) ?? [];
  if (!words.length) return topics;
  return topics.map(topic => ({ topic, score: words.reduce((sum, word) => sum + Number(`${topic.title} ${topic.terms}`.toLowerCase().includes(word)), 0) })).filter(x => x.score).sort((a, b) => b.score - a.score).map(x => x.topic).slice(0, 4);
}
