import { requireSession } from "@/lib/auth/session";
import { db } from "@/lib/db";
import { updateBookingAction } from "./actions";
export const metadata={title:"Booking requests",robots:{index:false,follow:false}};
export default async function BookingsPage({searchParams}:{searchParams:Promise<{status?:string;page?:string;error?:string}>}){
 const s=await requireSession();if(!["OWNER","ADMIN","MANAGER"].includes(s.role))return<section className="panel entity-form"><h1>Booking requests</h1><p>An owner, admin or manager account is required.</p></section>;
 const search=await searchParams;const status=["REQUESTED","CONTACTED","CLOSED"].includes(search.status??"")?search.status!:"REQUESTED";
 const page=Math.max(1,Math.min(10000,Number.parseInt(search.page??"1",10)||1));const where={organizationId:s.organizationId,status};
 const [total,requests]=await Promise.all([db.bookingRequest.count({where}),db.bookingRequest.findMany({where,include:{property:{select:{name:true}},roomType:{select:{name:true}}},orderBy:[{createdAt:"desc"},{id:"desc"}],take:30,skip:(page-1)*30})]);
 return<><div className="page-heading-row"><div><p className="eyebrow">Website requests</p><h1>Bookings</h1><p>{total} {status.toLowerCase()} requests. These requests do not reserve rooms or record payments.</p></div></div>
 <section className="panel entity-form"><form><label className="field-group"><span>Status</span><select name="status" defaultValue={status}><option value="REQUESTED">New requests</option><option value="CONTACTED">Contacted</option><option value="CLOSED">Closed</option></select></label><button className="secondary-button">Show requests</button></form>{search.error&&<p className="form-error" role="alert">The update could not be confirmed. Refresh and try again.</p>}<p>Contact the student to confirm availability and payment instructions. Use Students, Check-in / Check-out and Payments to complete their registration, allocation and verified payment.</p></section>
 <section className="panel mt-5"><div className="table-scroll"><table className="data-table"><thead><tr><th>Reference / hostel</th><th>Student</th><th>Room / move-in</th><th>Received</th><th>Status</th></tr></thead><tbody>{requests.map(r=><tr key={r.id}><td>{r.reference}<br/>{r.property.name}</td><td>{r.fullName}<br/><a href={`tel:${r.phone}`}>{r.phone}</a>{r.email&&<><br/><a href={`mailto:${r.email}`}>{r.email}</a></>}</td><td>{r.roomType.name}<br/>{r.preferredMoveIn.toISOString().slice(0,10)}</td><td>{new Intl.DateTimeFormat("en-KE",{dateStyle:"medium",timeStyle:"short",timeZone:"Africa/Nairobi"}).format(r.createdAt)} EAT</td><td><form action={updateBookingAction}><input name="id" type="hidden" value={r.id}/><label><span className="sr-only">Status for {r.reference}</span><select name="status" defaultValue={r.status}><option value="REQUESTED">New request</option><option value="CONTACTED">Contacted</option><option value="CLOSED">Closed</option></select></label><button className="secondary-button">Save</button></form></td></tr>)}</tbody></table></div>{!requests.length&&<p>No requests in this status.</p>}<p>Page {page}</p>{page>1&&<a href={`/bookings?status=${status}&page=${page-1}`}>Previous</a>}{page*30<total&&<a href={`/bookings?status=${status}&page=${page+1}`}>Next</a>}</section></>;
}
