import Link from "next/link";
import { Archive, CalendarDays, CircleCheck, Eye, RotateCcw, UserPlus } from "lucide-react";
import { BreakDecisionForm, BreakPeriodForm } from "@/components/break-forms";
import { requireSession } from "@/lib/auth/session";
import { db } from "@/lib/db";
import { cancelBreakReturnAction, clearBreakReservationAction, confirmBreakReturnAction } from "./actions";

const statusLabel: Record<string, string> = { RESERVED_FREE: "Reserved free", CLEARANCE_REQUIRED: "Clear before break", RETURN_CONFIRMED: "Return confirmed", VACATED_CLEARED: "Cleared", CHARGED: "Break charged", PENDING: "Pending", RETURN_CANCELLED: "Return cancelled" };

export default async function OccupancyPage() {
  const session = await requireSession();
  const canManage = session.role !== "CARETAKER";
  const [periods, occupancies, reservations, organization] = await Promise.all([
    db.breakPeriod.findMany({ where: { organizationId: session.organizationId, status: { in: ["UPCOMING", "ACTIVE"] } }, orderBy: { startDate: "desc" } }),
    db.occupancy.findMany({ where: { organizationId: session.organizationId, status: "ACTIVE" }, include: { student: true, room: true }, orderBy: { student: { fullName: "asc" } } }),
    db.breakReservation.findMany({ where: { organizationId: session.organizationId }, include: { student: true, room: true, breakPeriod: true, charge: { include: { payments: { where: { reversedAt: null } } } } }, orderBy: { createdAt: "desc" } }),
    db.organization.findUniqueOrThrow({ where: { id: session.organizationId }, select: { defaultBreakMonths: true } }),
  ]);
  return <div><div className="page-heading-row"><div><p className="eyebrow">Occupancy management</p><h1>Check-in and check-out</h1><p>Manage active stays, room transfers, clearance and break reservations.</p></div>{canManage ? <Link className="primary-button no-underline" href="/occupancy/check-in"><UserPlus size={17} /> Allocate paid student</Link> : null}</div>
    <section className="panel overflow-hidden"><div className="panel-heading"><div><p className="panel-kicker">Current residents</p><h2>{occupancies.length} active occupanc{occupancies.length === 1 ? "y" : "ies"}</h2></div></div>{occupancies.length ? <div className="table-scroll"><table className="data-table"><thead><tr><th>Student</th><th>Room</th><th>Check-in</th><th>Status</th><th /></tr></thead><tbody>{occupancies.map((item) => <tr key={item.id}><td><strong>{item.student.fullName}</strong></td><td>Room {item.room.number}</td><td>{item.checkInAt.toLocaleDateString("en-KE", { timeZone: "UTC" })}</td><td><span className="status-pill status-full">Active</span></td><td><Link className="table-action" href={`/occupancy/${item.id}`}><Eye size={14} /> View</Link></td></tr>)}</tbody></table></div> : <div className="inline-empty"><UserPlus size={25} /><strong>No active occupants</strong><p>Check in a student to allocate a room and generate rent.</p></div>}</section>
    <section className="policy-banner"><Archive size={22} /><div><strong>Conditional free reservation</strong><p>A returning student pays no break rent. If they later vacate, the break charge is created only when belongings remained in the room.</p></div></section>
    {canManage ? <div className="dashboard-grid mt-5"><section className="panel"><div className="panel-heading"><div><p className="panel-kicker">Configuration</p><h2>Create break period</h2></div><CalendarDays size={19} /></div><BreakPeriodForm defaultMonths={organization.defaultBreakMonths} /></section><section className="panel"><div className="panel-heading"><div><p className="panel-kicker">Student intention</p><h2>Record break decision</h2></div><RotateCcw size={19} /></div><BreakDecisionForm periods={periods.map((item) => ({ id: item.id, label: item.name }))} occupancies={occupancies.map((item) => ({ id: item.id, label: `${item.student.fullName} · Room ${item.room.number}` }))} /></section></div> : null}
    <section className="panel mt-5 overflow-hidden"><div className="panel-heading"><div><p className="panel-kicker">Break register</p><h2>{reservations.length} reservation{reservations.length === 1 ? "" : "s"}</h2></div></div>{reservations.length ? <div className="table-scroll"><table className="data-table break-table"><thead><tr><th>Student</th><th>Room</th><th>Break</th><th>Belongings</th><th>Potential charge</th><th>Status</th>{canManage ? <th>Action</th> : null}</tr></thead><tbody>{reservations.map((item) => <tr key={item.id}><td><strong>{item.student.fullName}</strong></td><td>Room {item.room.number}</td><td>{item.breakPeriod.name}</td><td>{item.belongingsStored ? "Stored" : "None"}</td><td>KES {Number(item.potentialCharge).toLocaleString("en-KE")}</td><td><span className="status-pill status-partial">{statusLabel[item.status]}</span></td>{canManage ? <td><div className="row-actions">{item.status === "RESERVED_FREE" ? <><form action={confirmBreakReturnAction}><input name="reservationId" type="hidden" value={item.id} /><button className="table-action"><CircleCheck size={14} /> Confirm return</button></form><form action={cancelBreakReturnAction}><input name="reservationId" type="hidden" value={item.id} /><button className="table-action danger-link">Move out</button></form></> : null}{item.status === "CLEARANCE_REQUIRED" ? <form action={clearBreakReservationAction}><input name="reservationId" type="hidden" value={item.id} /><button className="table-action"><CircleCheck size={14} /> Mark cleared</button></form> : null}{item.charge ? <span className="muted-note">Charge created</span> : null}</div></td> : null}</tr>)}</tbody></table></div> : <div className="inline-empty"><CalendarDays size={25} /><strong>No break decisions recorded</strong><p>Create a break period and record each active student’s intention.</p></div>}</section>
  </div>;
}
