"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { z } from "zod";
import { requireSession } from "@/lib/auth/session";
import { db } from "@/lib/db";
export type AssetFormState = { error: string };
const schema = z.object({ roomId: z.string().optional(), name: z.string().trim().min(2).max(100), category: z.enum(["BED", "MATTRESS", "CHAIR", "TABLE", "CURTAIN", "KEY", "SOCKET", "LIGHT", "OTHER"]), assetCode: z.string().trim().max(50).optional(), quantity: z.coerce.number().int().min(1).max(100), condition: z.enum(["NEW", "GOOD", "FAIR", "DAMAGED", "MISSING", "NOT_APPLICABLE"]), notes: z.string().trim().max(500).optional(), active: z.boolean() });
async function manager() { const session = await requireSession(); if (session.role === "CARETAKER") redirect("/assets"); return session; }
function parse(formData: FormData) { return schema.safeParse({ roomId: formData.get("roomId") || undefined, name: formData.get("name"), category: formData.get("category"), assetCode: formData.get("assetCode") || undefined, quantity: formData.get("quantity"), condition: formData.get("condition"), notes: formData.get("notes") || undefined, active: formData.get("active") === "on" }); }
export async function createAssetAction(_state: AssetFormState, formData: FormData): Promise<AssetFormState> { const session = await manager(); const parsed = parse(formData); if (!parsed.success) return { error: parsed.error.issues[0]?.message ?? "Check the asset details." }; if (parsed.data.roomId && !(await db.room.findFirst({ where: { id: parsed.data.roomId, organizationId: session.organizationId } }))) return { error: "The selected room is unavailable." }; if (parsed.data.assetCode && await db.hostelAsset.findFirst({ where: { organizationId: session.organizationId, assetCode: parsed.data.assetCode } })) return { error: "That asset code is already in use." }; await db.$transaction(async (tx) => { const asset = await tx.hostelAsset.create({ data: { organizationId: session.organizationId, roomId: parsed.data.roomId || null, name: parsed.data.name, category: parsed.data.category, assetCode: parsed.data.assetCode || null, quantity: parsed.data.quantity, condition: parsed.data.condition, notes: parsed.data.notes || null, active: parsed.data.active } }); await tx.auditLog.create({ data: { organizationId: session.organizationId, actorUserId: session.userId, action: "HOSTEL_ASSET_CREATED", entityType: "HostelAsset", entityId: asset.id, metadata: { name: asset.name, category: asset.category, roomId: asset.roomId } } }); }); revalidatePath("/assets"); redirect("/assets"); }
export async function updateAssetAction(assetId: string, _state: AssetFormState, formData: FormData): Promise<AssetFormState> { const session = await manager(); const parsed = parse(formData); if (!parsed.success) return { error: parsed.error.issues[0]?.message ?? "Check the asset details." }; const asset = await db.hostelAsset.findFirst({ where: { id: assetId, organizationId: session.organizationId } }); if (!asset) return { error: "The asset is unavailable." }; if (parsed.data.assetCode && await db.hostelAsset.findFirst({ where: { organizationId: session.organizationId, assetCode: parsed.data.assetCode, NOT: { id: assetId } } })) return { error: "That asset code is already in use." }; await db.$transaction([db.hostelAsset.update({ where: { id: asset.id }, data: { roomId: parsed.data.roomId || null, name: parsed.data.name, category: parsed.data.category, assetCode: parsed.data.assetCode || null, quantity: parsed.data.quantity, condition: parsed.data.condition, notes: parsed.data.notes || null, active: parsed.data.active } }), db.auditLog.create({ data: { organizationId: session.organizationId, actorUserId: session.userId, action: "HOSTEL_ASSET_UPDATED", entityType: "HostelAsset", entityId: asset.id, metadata: { condition: parsed.data.condition, roomId: parsed.data.roomId || null } } })]); revalidatePath("/assets"); redirect("/assets"); }
