import Link from "next/link";
import { AlertCircle, Banknote, FilePlus2, ListChecks, Plus, ReceiptText, RotateCcw, WalletCards } from "lucide-react";
import { requireSession } from "@/lib/auth/session";
import { db } from "@/lib/db";

const money = (value: number) => `KES ${value.toLocaleString("en-KE", { maximumFractionDigits: 2 })}`;
const chargeType: Record<string, string> = { SEMESTER_RENT: "Semester rent", BREAK_ACCOMMODATION: "Break accommodation", DAMAGE: "Damage", OTHER: "Other" };

export default async function PaymentsPage() {
  const session = await requireSession();
  const canManage = session.role !== "CARETAKER";
  const canReverse = session.role === "OWNER" || session.role === "ADMIN";
  const [charges, payments] = await Promise.all([
    db.charge.findMany({ where: { organizationId: session.organizationId }, include: { student: true, payments: { where: { reversedAt: null } } }, orderBy: { dueDate: "asc" } }),
    db.payment.findMany({ where: { organizationId: session.organizationId }, include: { student: true, charge: true, mpesaTransaction: true }, orderBy: { paidAt: "desc" }, take: 20 }),
  ]);
  const rows = charges.map((item) => { const paid = item.payments.reduce((sum, payment) => sum + Number(payment.amount), 0); return { ...item, amountNumber: Number(item.amount), paid, balance: Math.max(0, Number(item.amount) - paid) }; });
  const expected = rows.reduce((sum, item) => sum + item.amountNumber, 0);
  const collected = rows.reduce((sum, item) => sum + item.paid, 0);
  const outstanding = rows.reduce((sum, item) => sum + item.balance, 0);
  const overdue = rows.filter((item) => item.balance > 0 && item.dueDate < new Date()).reduce((sum, item) => sum + item.balance, 0);

  return <div><div className="page-heading-row"><div><p className="eyebrow">Rent collection</p><h1>Payments</h1><p>Manage rent charges, partial payments, balances and printable receipts.</p></div>{canManage ? <div className="heading-actions"><Link className="secondary-button no-underline" href="/payments/reconciliation"><ListChecks size={17} /> Reconcile M-Pesa</Link><Link className="secondary-button no-underline" href="/payments/new?mode=charge"><FilePlus2 size={17} /> Add charge</Link><Link className="primary-button no-underline" href="/payments/new"><Plus size={17} /> Record payment</Link></div> : null}</div>
    <section className="room-summary-grid"><article className="compact-stat"><span className="metric-icon metric-blue"><Banknote size={22} /></span><div><p>Total charges</p><strong>{money(expected)}</strong></div></article><article className="compact-stat"><span className="metric-icon metric-green"><WalletCards size={22} /></span><div><p>Collected</p><strong>{money(collected)}</strong></div></article><article className="compact-stat"><span className="metric-icon metric-violet"><ReceiptText size={22} /></span><div><p>Outstanding</p><strong>{money(outstanding)}</strong></div></article><article className="compact-stat"><span className="metric-icon metric-red"><AlertCircle size={22} /></span><div><p>Overdue</p><strong>{money(overdue)}</strong></div></article></section>
    <section className="panel mt-5 overflow-hidden"><div className="panel-heading"><div><p className="panel-kicker">Receivables</p><h2>Student balances</h2></div></div>{rows.length ? <div className="table-scroll"><table className="data-table payments-table"><thead><tr><th>Student</th><th>Charge</th><th>Total</th><th>Paid</th><th>Balance</th><th>Due date</th><th>Status</th>{canManage ? <th>Action</th> : null}</tr></thead><tbody>{rows.map((item) => { const isOverdue = item.balance > 0 && item.dueDate < new Date(); return <tr key={item.id}><td><strong>{item.student.fullName}</strong></td><td>{chargeType[item.type]}<small className="table-subtext">{item.description}</small></td><td>{money(item.amountNumber)}</td><td>{money(item.paid)}</td><td><strong>{money(item.balance)}</strong></td><td>{item.dueDate.toLocaleDateString("en-KE", { timeZone: "UTC" })}</td><td><span className={`status-pill ${item.balance === 0 ? "status-full" : isOverdue ? "status-maintenance" : "status-partial"}`}>{item.balance === 0 ? "Fully paid" : isOverdue ? "Overdue" : item.paid ? "Part paid" : "Unpaid"}</span></td>{canManage ? <td>{item.balance > 0 ? <Link className="table-action" href={`/payments/new?chargeId=${item.id}`}>Record payment</Link> : null}</td> : null}</tr>; })}</tbody></table></div> : <div className="inline-empty"><ReceiptText size={25} /><strong>No charges yet</strong><p>Create a semester rent charge before recording a payment.</p></div>}</section>
    <section className="panel mt-5 overflow-hidden"><div className="panel-heading"><div><p className="panel-kicker">Receipt history</p><h2>Recent payments</h2></div></div>{payments.length ? <div className="table-scroll"><table className="data-table"><thead><tr><th>Receipt</th><th>Student</th><th>Amount</th><th>Method</th><th>Reference</th><th>Date</th><th>Status</th><th>Actions</th></tr></thead><tbody>{payments.map((payment) => <tr className={payment.reversedAt ? "reversed-row" : ""} key={payment.id}><td><strong>{payment.receiptNumber}</strong></td><td>{payment.student.fullName}</td><td>{money(Number(payment.amount))}</td><td>{payment.method.replaceAll("_", " ")}</td><td>{payment.reference || "—"}</td><td>{payment.paidAt.toLocaleDateString("en-KE", { timeZone: "UTC" })}</td><td>{payment.reversedAt ? <span className="status-pill status-maintenance">Reversed</span> : payment.method === "MPESA" ? <span className={`status-pill ${payment.mpesaTransaction?.status === "MATCHED" ? "status-full" : "status-partial"}`}>{payment.mpesaTransaction?.status === "MATCHED" ? "Reconciled" : "Unreconciled"}</span> : <span className="status-pill status-full">Active</span>}</td><td><div className="row-actions"><Link className="table-action" href={`/payments/${payment.id}/receipt`}><ReceiptText size={14} /> Receipt</Link>{canReverse && !payment.reversedAt ? <Link className="danger-link" href={`/payments/${payment.id}/reverse`}><RotateCcw size={14} /> Reverse</Link> : null}</div></td></tr>)}</tbody></table></div> : <div className="inline-empty"><WalletCards size={25} /><strong>No payments recorded</strong></div>}</section>
  </div>;
}
