import Link from "next/link";
import { AlertCircle, ArrowRight, Banknote, BedDouble, CircleCheck, DoorOpen, Users, WalletCards } from "lucide-react";
import { DynamicGreeting } from "@/components/dynamic-greeting";
import { requireSession } from "@/lib/auth/session";
import { db } from "@/lib/db";
import { compareRooms } from "@/lib/natural-sort";
import { getEffectiveRoomStatus } from "@/lib/rooms";

const money = (value: number) => `KES ${value.toLocaleString("en-KE", { maximumFractionDigits: 0 })}`;
export default async function DashboardPage() {
  const session = await requireSession();
  const kenyaHour = (new Date().getUTCHours() + 3) % 24;
  const initialGreeting = kenyaHour < 12 ? "Good morning" : kenyaHour < 18 ? "Good afternoon" : "Good evening";
  const semester = await db.semester.findFirst({ where: { organizationId: session.organizationId, status: "ACTIVE" } });
  const [rooms, students, charges, recentPayments] = await Promise.all([
    db.room.findMany({ where: { organizationId: session.organizationId }, include: { roomType: true, occupancies: { where: { status: "ACTIVE" }, include: { student: true } }, breakReservations: { where: { status: { in: ["RESERVED_FREE", "CHARGED"] }, intent: "RETURNING", clearedAt: null }, include: { student: true } } }, orderBy: { number: "asc" } }),
    db.student.count({ where: { organizationId: session.organizationId, status: "ACTIVE" } }),
    db.charge.findMany({ where: { organizationId: session.organizationId, ...(semester ? { semesterId: semester.id } : {}) }, include: { payments: { where: { reversedAt: null } } } }),
    db.payment.findMany({ where: { organizationId: session.organizationId, reversedAt: null }, include: { student: true, charge: true }, orderBy: { paidAt: "desc" }, take: 6 }),
  ]);
  rooms.sort(compareRooms);
  const roomData = rooms.map((room) => { const capacity = room.capacityOverride ?? room.roomType.defaultCapacity; const heldIds = new Set([...room.occupancies.map((item) => item.studentId), ...room.breakReservations.map((item) => item.studentId)]); return { ...room, capacity, held: heldIds.size, effectiveStatus: getEffectiveRoomStatus(room.status, heldIds.size, capacity) }; });
  const vacant = roomData.filter((room) => room.effectiveStatus === "VACANT").length;
  const occupied = roomData.filter((room) => ["FULL", "PARTIALLY_OCCUPIED"].includes(room.effectiveStatus)).length;
  const maintenance = roomData.filter((room) => room.effectiveStatus === "MAINTENANCE").length;
  const expected = charges.reduce((sum, charge) => sum + Number(charge.amount), 0);
  const collected = charges.reduce((sum, charge) => sum + charge.payments.reduce((paid, item) => paid + Number(item.amount), 0), 0);
  const outstanding = Math.max(0, expected - collected);
  const overdueCharges = charges.filter((charge) => charge.dueDate < new Date() && Number(charge.amount) > charge.payments.reduce((sum, item) => sum + Number(item.amount), 0));
  const fullyPaid = charges.filter((charge) => Number(charge.amount) <= charge.payments.reduce((sum, item) => sum + Number(item.amount), 0)).length;
  const collectionPercent = expected ? Math.min(100, Math.round((collected / expected) * 100)) : 0;
  return <div><div className="page-heading-row"><div><p className="eyebrow">Live semester overview</p><DynamicGreeting firstName={session.name.split(" ")[0]} initialGreeting={initialGreeting} /><p>{semester?.name ?? "No active semester"} · updated from current records</p></div><Link className="secondary-button no-underline" href="/payments/new"><Banknote size={18} /> Record payment</Link></div>
    <section className="metric-grid"><article className="metric-card"><span className="metric-icon metric-blue"><BedDouble size={23} /></span><div><p>Total rooms</p><strong>{rooms.length}</strong></div></article><article className="metric-card"><span className="metric-icon metric-green"><Users size={23} /></span><div><p>Occupied rooms</p><strong>{occupied}</strong></div></article><article className="metric-card"><span className="metric-icon metric-sky"><DoorOpen size={23} /></span><div><p>Vacant rooms</p><strong>{vacant}</strong></div></article><article className="metric-card"><span className="metric-icon metric-violet"><Users size={23} /></span><div><p>Active students</p><strong>{students}</strong></div></article>{maintenance > 0 ? <article className="metric-card"><span className="metric-icon metric-red"><AlertCircle size={23} /></span><div><p>Maintenance rooms</p><strong>{maintenance}</strong><small>Not available for allocation</small></div></article> : null}</section>
    <section className="finance-strip"><div><span className="metric-icon metric-blue"><Banknote size={23} /></span><div><p>Expected rent</p><strong>{money(expected)}</strong><small>{semester?.name ?? "All recorded charges"}</small></div></div><div><span className="metric-icon metric-green"><WalletCards size={23} /></span><div><p>Collected</p><strong>{money(collected)}</strong><small>{collectionPercent}% collected</small><div className="progress-track"><span className="bg-emerald-500" style={{ width: `${collectionPercent}%` }} /></div></div></div><div><span className="metric-icon metric-red"><AlertCircle size={23} /></span><div><p>Outstanding</p><strong>{money(outstanding)}</strong><small>{overdueCharges.length} overdue charge(s)</small></div></div><Link className="overdue-card" href="/reports"><span className="alert-icon"><AlertCircle size={20} /></span><span><strong>Overdue balances</strong><small>{overdueCharges.length} require follow-up</small></span><ArrowRight className="ml-auto" size={17} /></Link></section>
    <div className="dashboard-grid mt-5"><section className="panel"><div className="panel-heading"><div><p className="panel-kicker">Live allocation</p><h2>Room occupancy</h2></div><Link href="/rooms">View rooms <ArrowRight size={15} /></Link></div><div className="room-grid">{roomData.slice(0, 9).map((room) => <article className="room-tile" key={room.id}><div className="flex items-center gap-2"><span className={room.effectiveStatus === "VACANT" ? "status-dot status-vacant" : "status-dot"} /><strong>Room {room.number}</strong></div><p>{room.effectiveStatus.replaceAll("_", " ")}</p><small>{room.held}/{room.capacity} spaces held</small></article>)}</div></section><section className="panel"><div className="panel-heading"><div><p className="panel-kicker">Attention needed</p><h2>Live alerts</h2></div></div><div className="alert-list"><Link href="/reports"><span className="alert-icon"><AlertCircle size={18} /></span><span><strong>Overdue</strong><small>Outstanding past due date</small></span><b>{overdueCharges.length}</b><ArrowRight size={15} /></Link><Link href="/payments"><span className="alert-icon alert-icon-green"><CircleCheck size={18} /></span><span><strong>Fully paid</strong><small>Charges cleared</small></span><b>{fullyPaid}</b><ArrowRight size={15} /></Link><Link href="/rooms"><span className="alert-icon alert-icon-blue"><DoorOpen size={18} /></span><span><strong>Vacant rooms</strong><small>Available accommodation</small></span><b>{vacant}</b><ArrowRight size={15} /></Link></div></section></div>
    <section className="panel mt-5 overflow-hidden"><div className="panel-heading"><div><p className="panel-kicker">Latest activity</p><h2>Recent payments</h2></div><Link href="/payments">View all <ArrowRight size={15} /></Link></div><div className="table-scroll"><table className="data-table"><thead><tr><th>Student</th><th>Receipt</th><th>Amount</th><th>Charge</th><th>Date</th></tr></thead><tbody>{recentPayments.map((payment) => <tr key={payment.id}><td><strong>{payment.student.fullName}</strong></td><td>{payment.receiptNumber}</td><td>{money(Number(payment.amount))}</td><td>{payment.charge.description}</td><td>{payment.paidAt.toLocaleDateString("en-KE", { timeZone: "UTC" })}</td></tr>)}</tbody></table></div></section>
  </div>;
}
