import Link from "next/link";
import { requireSession } from "@/lib/auth/session";
import { db } from "@/lib/db";
import { invitationManager } from "@/lib/portal-invitations";
import { InvitationRunForm } from "@/components/invitation-run-form";
import { invitationSettingsAction,reissueInvitationAction } from "./actions";
export const dynamic="force-dynamic";
export default async function InvitationsPage(){
 const s=await requireSession();if(!(await invitationManager(db,s)))return <section className="panel"><h1>Account invitations unavailable</h1><p>Only owners and administrators can manage account activation.</p></section>;
 const [settings,items]=await Promise.all([db.communicationSettings.findUnique({where:{organizationId:s.organizationId}}),db.tenantPortalInvitation.findMany({where:{organizationId:s.organizationId},include:{student:{select:{fullName:true}}},orderBy:{createdAt:"desc"},take:100})]);
 return <div><div className="page-heading-row"><div><h1>Automatic account invitations</h1><p>Email current registered tenants a private link to set their own password.</p></div><Link className="secondary-button" href="/communications">Communication centre</Link></div><section className="panel entity-form"><form action={invitationSettingsAction} className="entity-form"><label className="check-field"><input name="inviteEnabled" type="checkbox" defaultChecked={settings?.inviteEnabled??false}/>Automatically invite tenants who have never activated portal access</label><p>The daily run is at 8 a.m. Nairobi time, with up to 30 invitations per run. A registered student email is needed for automatic delivery. Invitations expire 72 hours after the first send attempt. Existing accounts and explicitly disabled access are excluded. WhatsApp automatic sending requires a Business sender connection.</p><button className="secondary-button">Save invitation setting</button></form><InvitationRunForm/></section><section className="panel entity-form mt-5"><h2>Latest 100 invitation records</h2>{items.length?items.map(i=><article key={i.id}><strong>{i.student.fullName}</strong><p>{i.status.replaceAll("_"," ")}{i.recipient?" · "+i.recipient:""}</p>{i.expiresAt?<small>Expires {i.expiresAt.toLocaleString("en-KE",{timeZone:"Africa/Nairobi"})}</small>:null}{i.error?<p>{i.error}</p>:null}{["FAILED","MISSING_EMAIL","EXPIRED","INELIGIBLE"].includes(i.status)&&!i.usedAt?<form action={reissueInvitationAction}><input name="id" type="hidden" value={i.id}/><button className="secondary-button">Queue new invitation after checking the student record</button></form>:null}</article>):<p>No invitations processed yet.</p>}</section></div>;
}
