import Link from 'next/link';
import {requireSession} from '@/lib/auth/session';
import {db} from '@/lib/db';
import {PropertyProfileForm} from '@/components/property-profile-form';
import {AccommodationTypeForm,PublicationForm} from '@/components/landlord-setup-forms';
import {publicationProblems} from '@/lib/landlord-onboarding-policy';
export default async function Setup(){
 const session=await requireSession();const canManage=['OWNER','ADMIN'].includes(session.role);
 const properties=await db.property.findMany({where:{organizationId:session.organizationId,active:true},select:{id:true,name:true,physicalAddress:true,countryCode:true,city:true,region:true,postalCode:true,latitude:true,longitude:true,timeZone:true,rentPaymentMethods:true,phone:true,email:true,publicDescription:true,customDomain:true,publicListing:true},orderBy:{createdAt:'asc'}});
 const rooms=await db.room.findMany({where:{organizationId:session.organizationId},select:{propertyId:true,status:true,roomType:{select:{active:true,monthlyRate:true,semesterRate:true,defaultCapacity:true}}}});
 return <div className="settings-stack"><div className="page-heading-row"><div><p className="eyebrow">Landlord onboarding</p><h1>Set up your hostel website</h1><p>Complete your property details, configure rates and rooms, then review and publish. Your public website uses your own hostel name.</p></div></div>{!canManage?<p>Ask the owner to complete setup.</p>:<>{properties.map(p=>{const count=rooms.filter(r=>r.propertyId===p.id&&!['INACTIVE','MAINTENANCE'].includes(r.status)&&r.roomType.active&&Number(r.roomType.monthlyRate)>0&&Number(r.roomType.semesterRate)>0&&r.roomType.defaultCapacity>0).length;const problems=publicationProblems(p,count);return <section key={p.id} className="settings-stack"><PropertyProfileForm property={p}/><div className="panel"><h2>Website readiness</h2><p>Address: {p.customDomain??'Not assigned'}</p><p>{count} configured room{count===1?'':'s'}</p>{problems.length?<ul>{problems.map(problem=><li key={problem}>{problem}</li>)}</ul>:<p>Property details and rooms are ready for your review.</p>}{p.publicListing&&p.customDomain&&<a href={`https://${p.customDomain}`} target="_blank" rel="noreferrer">View published website</a>}</div>{session.role==='OWNER'&&<PublicationForm propertyId={p.id} published={p.publicListing} ready={!problems.length}/>}</section>;})}<AccommodationTypeForm/><div className="panel"><h2>Add your rooms and staff</h2><p><Link href="/website">Manage website pictures →</Link></p><p><Link href="/rooms/new">Add a room →</Link></p><p><Link href="/users">Manage staff →</Link></p><p><a href="https://systeminone.com/account">Review platform access →</a></p></div></>}</div>;
}
