"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { z } from "zod";
import { requireSession } from "@/lib/auth/session";
import { db } from "@/lib/db";

export type PropertyFormState = { error: string };
const schema = z.object({ occupancyId: z.string().min(1), name: z.string().trim().min(2).max(100), category: z.enum(["LAPTOP", "SUITCASE", "MATTRESS", "ELECTRONICS", "BICYCLE", "OTHER"]), description: z.string().trim().max(300).optional(), checkInCondition: z.enum(["NEW", "GOOD", "FAIR", "DAMAGED", "MISSING", "NOT_APPLICABLE"]), checkoutCondition: z.union([z.literal(""), z.enum(["NEW", "GOOD", "FAIR", "DAMAGED", "MISSING", "NOT_APPLICABLE"])]), notes: z.string().trim().max(500).optional() });
async function manager() { const session = await requireSession(); if (session.role === "CARETAKER") redirect("/student-property"); return session; }
function parse(formData: FormData) { return schema.safeParse({ occupancyId: formData.get("occupancyId"), name: formData.get("name"), category: formData.get("category"), description: formData.get("description") || undefined, checkInCondition: formData.get("checkInCondition"), checkoutCondition: formData.get("checkoutCondition") || "", notes: formData.get("notes") || undefined }); }

export async function createPropertyAction(_state: PropertyFormState, formData: FormData): Promise<PropertyFormState> { const session = await manager(); const parsed = parse(formData); if (!parsed.success) return { error: parsed.error.issues[0]?.message ?? "Check the property details." }; const occupancy = await db.occupancy.findFirst({ where: { id: parsed.data.occupancyId, organizationId: session.organizationId, status: "ACTIVE" } }); if (!occupancy) return { error: "Select an active student occupancy." }; await db.$transaction(async (tx) => { const item = await tx.studentPropertyItem.create({ data: { occupancyId: occupancy.id, name: parsed.data.name, category: parsed.data.category, description: parsed.data.description || null, checkInCondition: parsed.data.checkInCondition, checkoutCondition: parsed.data.checkoutCondition || null, notes: parsed.data.notes || null } }); await tx.auditLog.create({ data: { organizationId: session.organizationId, actorUserId: session.userId, action: "STUDENT_PROPERTY_ADDED", entityType: "StudentPropertyItem", entityId: item.id, metadata: { occupancyId: occupancy.id, category: item.category, name: item.name } } }); }); revalidatePath("/student-property"); revalidatePath(`/occupancy/${occupancy.id}`); redirect("/student-property"); }

export async function updatePropertyAction(itemId: string, _state: PropertyFormState, formData: FormData): Promise<PropertyFormState> { const session = await manager(); const parsed = parse(formData); if (!parsed.success) return { error: parsed.error.issues[0]?.message ?? "Check the property details." }; const item = await db.studentPropertyItem.findFirst({ where: { id: itemId, occupancy: { organizationId: session.organizationId } } }); const occupancy = await db.occupancy.findFirst({ where: { id: parsed.data.occupancyId, organizationId: session.organizationId } }); if (!item || !occupancy) return { error: "The property record is unavailable." }; await db.$transaction([db.studentPropertyItem.update({ where: { id: item.id }, data: { occupancyId: occupancy.id, name: parsed.data.name, category: parsed.data.category, description: parsed.data.description || null, checkInCondition: parsed.data.checkInCondition, checkoutCondition: parsed.data.checkoutCondition || null, notes: parsed.data.notes || null } }), db.auditLog.create({ data: { organizationId: session.organizationId, actorUserId: session.userId, action: "STUDENT_PROPERTY_UPDATED", entityType: "StudentPropertyItem", entityId: item.id, metadata: { category: parsed.data.category, name: parsed.data.name } } })]); revalidatePath("/student-property"); revalidatePath(`/occupancy/${occupancy.id}`); redirect("/student-property"); }
