import Link from "next/link";
import { randomUUID } from "node:crypto";
import { requireSession } from "@/lib/auth/session";
import { db } from "@/lib/db";
import { communicationManager, tenantWhere } from "@/lib/communications";
import { CommunicationForm } from "@/components/communication-form";
import { settingsAction, retryEmailAction } from "./actions";
import styles from "./whatsapp/whatsapp.module.css";
import { manualDeliveryLabels } from "@/lib/whatsapp-policy";
export const dynamic="force-dynamic";
export default async function CommunicationsPage(){
 const session=await requireSession(); if(!(await communicationManager(db,session))) return <div className="panel"><h1>Communications unavailable</h1><p>Only active owners, administrators and managers can publish tenant communications.</p></div>;
 const [students,settings,history]=await Promise.all([db.student.findMany({where:tenantWhere(session.organizationId),select:{id:true,fullName:true},orderBy:{fullName:"asc"},take:5000}),db.communicationSettings.findUnique({where:{organizationId:session.organizationId}}),db.tenantMessage.findMany({where:{organizationId:session.organizationId},include:{student:{select:{fullName:true}}},orderBy:{createdAt:"desc"},take:100})]);
 const notificationIds=history.flatMap(m=>m.notificationId?[m.notificationId]:[]);
 const statuses=notificationIds.length?await db.notification.findMany({where:{organizationId:session.organizationId,id:{in:notificationIds}},select:{id:true,status:true}}):[];
 const delivery=new Map(statuses.map(n=>[n.id,manualDeliveryLabels[n.status]]));
 return <div className={styles.page}><div className="page-heading-row"><div><p className="eyebrow">Tenant communication</p><h1>Communication centre</h1><p>Private notices for all or selected current tenants. Guardians and public visitors are excluded.</p></div></div><div className={styles.actions}><Link className="primary-button" href="/communications/whatsapp">Open WhatsApp centre</Link><Link className="secondary-button" href="/communications/inbox">Open student inbox</Link><Link className="secondary-button" href="/communications/invitations">Account invitations</Link></div><CommunicationForm students={students} requestId={randomUUID()}/><form action={settingsAction} className="panel entity-form mt-5"><h2>Automatic reminders</h2><label className="check-field"><input name="balanceEnabled" type="checkbox" defaultChecked={settings?.balanceEnabled??false}/>Individual balances on the 7th and 10th each month</label><label className="check-field"><input name="holidayEnabled" type="checkbox" defaultChecked={settings?.holidayEnabled??false}/>Holiday arrangements during the seven days before an upcoming holiday</label><label className="check-field"><input name="emailCopies" type="checkbox" defaultChecked={settings?.emailCopies??false}/>Email copies of automatic reminders and management reply notifications</label><label className="check-field"><input name="whatsappCopies" type="checkbox" defaultChecked={settings?.whatsappCopies??false}/>Prepare WhatsApp copies of automatic reminders</label><p>Daily processing runs at 8 a.m. Nairobi time. Balances use recorded charges less unreversed payments. Holiday reminders use the holiday periods entered in the system. Examination wishes can be composed and scheduled above.</p><p>WhatsApp drafts appear in the WhatsApp centre and manual reminders queue. A WhatsApp Business sender is needed for automatic external delivery.</p><button className="secondary-button">Save automation settings</button></form><section className="panel entity-form mt-5"><h2>Latest 100 recipient records</h2>{history.length?history.map(m=><article key={m.id}><strong>{m.title} · {m.student.fullName}</strong><p style={{whiteSpace:"pre-wrap"}}>{m.body}</p><small>{m.publishAt.toLocaleString("en-KE",{timeZone:"Africa/Nairobi"})} · {m.publishAt>new Date()?"Scheduled":m.readAt?"Read in portal":"Available in portal"}{m.emailCopy?" · Email: "+m.emailStatus.replaceAll("_"," "):""}{m.whatsappCopy?(m.notificationId?" · WhatsApp: "+(delivery.get(m.notificationId)??"Draft unavailable"):" · WhatsApp copy pending"):""}</small>{m.emailError?<p>{m.emailError}</p>:null}{["FAILED","MISSING_EMAIL"].includes(m.emailStatus)?<form action={retryEmailAction}><input name="id" type="hidden" value={m.id}/><button className="secondary-button">Retry email after correcting details</button></form>:null}</article>):<p>No announcements yet.</p>}</section></div>;
}
