import Link from "next/link";
import Image from "next/image";
import { publicPropertyPhotos } from "@/lib/property-public-photos";
import { notFound } from "next/navigation";
import { BedDouble, MapPin } from "lucide-react";
import { db } from "@/lib/db";
import { requestPropertyContext } from "@/lib/property-host";
import { normalizeHost, publishedWhere } from "@/lib/property-host-policy";
import { activeBreakHoldWhere } from "@/lib/room-status";
import { getEffectiveRoomStatus } from "@/lib/rooms";
const money=(value:number)=>new Intl.NumberFormat("en-KE",{style:"currency",currency:"KES",maximumFractionDigits:0}).format(value);
export async function generateMetadata() {
 const {property}=await requestPropertyContext();
 if(!property)return {alternates:{canonical:"https://studentshostels.com/"}};
 const photo=(await publicPropertyPhotos(property.id,property.organizationId))[0];
 const description=property.publicDescription ?? `Rooms and accommodation at ${property.name}`;
 return {title:{absolute:property.name},description,alternates:{canonical:`https://${property.customDomain}/`},openGraph:{title:property.name,description,siteName:property.name,url:`https://${property.customDomain}/`,...(photo?.url?{images:[{url:photo.url,alt:photo.caption||property.name}]}:{})},twitter:{card:photo?.url?"summary_large_image" as const:"summary" as const,title:property.name,description,...(photo?.url?{images:[photo.url]}:{})}};
}
export default async function Home() {
 const context=await requestPropertyContext();
 if (!context.shared && !context.property) notFound();
 const p=context.property;
 const title=p?.name ?? "StudentsHostels";
 const listings=context.shared ? await db.property.findMany({where:{...publishedWhere(),customDomain:{not:null}},select:{id:true,name:true,customDomain:true,physicalAddress:true,publicDescription:true},orderBy:{name:"asc"},take:500}) : [];
 const rooms=p ? await db.room.findMany({where:{propertyId:p.id,organizationId:p.organizationId,property:publishedWhere(),roomType:{active:true,organizationId:p.organizationId}},select:{status:true,capacityOverride:true,roomType:{select:{id:true,name:true,defaultCapacity:true,monthlyRate:true,semesterRate:true,sharingMode:true}},occupancies:{where:{status:"ACTIVE",organizationId:p.organizationId},select:{studentId:true}},breakReservations:{where:{...activeBreakHoldWhere,organizationId:p.organizationId},select:{studentId:true}}}}) : [];
 const rates=new Map<string,{name:string;monthly:number;semester:number;available:number}>();
 for(const room of rooms){const type=room.roomType;const held=new Set([...room.occupancies,...room.breakReservations].map(x=>x.studentId)).size;const capacity=room.capacityOverride??type.defaultCapacity;const available=["VACANT","PARTIALLY_OCCUPIED"].includes(getEffectiveRoomStatus(room.status,held,capacity))?Math.max(0,capacity-held):0;const row=rates.get(type.id)??{name:type.name,monthly:Number(type.monthlyRate),semester:Number(type.semesterRate),available:0};row.available+=available;rates.set(type.id,row);}
 const photos=p ? await publicPropertyPhotos(p.id,p.organizationId) : [];
 const phone=p?.phone?.replace(/[^0-9+]/g,"");
 return <main className="marketing-site approved-home">
 <nav className="marketing-nav"><Link className="marketing-brand" href="/"><strong>{title}</strong><span>{p ? "Student accommodation" : "Find your student home"}</span></Link><div className="marketing-links">{p ? <><a href="#rooms">Rooms & rates</a>{photos.length>0 && <a href="#photos">Pictures</a>}<a href="#location">Contact</a></> : <a href="https://studentshostels.com">All hostels</a>}<a href={p ? "/tenant/login" : "https://studentshostels.com/tenant/login"}>Student portal</a><a href={p ? "/login" : "https://studentshostels.com/login"}>Management login</a></div></nav>
 <section className="approved-hero" id="home"><div className="approved-hero-copy"><span>{p ? "YOUR STUDENT HOME" : "STUDENT ACCOMMODATION"}</span><h1>{title}</h1><p>{p?.publicDescription ?? (p ? "Explore rooms, current rates and availability. Contact the hostel to arrange a viewing." : "Discover participating hostels, compare accommodation and contact each property directly.")}</p><div className="marketing-actions"><a className="primary-button" href="#rooms"><BedDouble size={18}/>{p ? "View rooms & availability" : "Explore hostels"}</a>{p && phone && <a className="secondary-button" href={`tel:${phone}`}>Call the hostel</a>}</div></div><div className="compound-showcase">{photos[0]?.url ? <div className="property-cover-image"><Image src={photos[0].url} alt={photos[0].caption || title} fill sizes="(max-width: 900px) 100vw, 50vw" unoptimized preload/></div> : <div className="compound-placeholder"><strong>{title}</strong><span>{p ? "Property photography will appear once approved by management." : "Independent hostels. One connected platform."}</span></div>}</div></section>
 {p && photos.length>0 && <section className="marketing-section" id="photos"><div className="marketing-section-head"><span>PICTURES</span><h2>Explore {p.name}</h2></div><div className="property-photo-grid">{photos.map(photo => <figure className="property-public-photo" key={photo.id}><div className="property-photo-preview"><Image src={photo.url!} alt={photo.caption || p.name} fill sizes="(max-width: 700px) 100vw, 33vw" unoptimized/></div>{photo.caption && <figcaption>{photo.caption}</figcaption>}</figure>)}</div></section>}
 <section className="marketing-section" id="rooms"><div className="marketing-section-head"><span>{p ? "ROOMS & RATES" : "HOSTEL DIRECTORY"}</span><h2>{p ? "Find the room that suits you." : "Choose your hostel."}</h2><p>{p ? "Availability is read from current room records. Confirm your booking with management before paying." : "Each hostel has its own website and management team."}</p></div><div className="marketing-room-grid">{p ? [...rates.entries()].map(([id,row])=><article className="marketing-room-card" key={id}><h3>{row.name}</h3><div className="marketing-prices"><span><small>Monthly</small><strong>{money(row.monthly)}</strong></span><span><small>Semester</small><strong>{money(row.semester)}</strong></span></div><p>{row.available} student place{row.available===1?"":"s"} currently available</p>{phone && <a className="room-enquiry" href={`tel:${phone}`}>Enquire about this room</a>}</article>) : listings.filter(l=>normalizeHost(l.customDomain)===l.customDomain).map(l=><article className="marketing-room-card" key={l.id}><h3>{l.name}</h3><p>{l.publicDescription}</p><p>{l.physicalAddress}</p><a className="room-enquiry" href={`https://${l.customDomain}`}>Visit hostel website</a></article>)}</div>{p && !rates.size && <p>Contact management for current room options.</p>}{!p && !listings.length && <p>Published hostels will appear here.</p>}</section>
 {p && <section className="public-split" id="location"><div><span className="marketing-chip"><MapPin size={16}/>LOCATION & CONTACT</span><h2>{p.name}</h2><p>{p.physicalAddress ?? "Contact management for directions."}</p>{phone && <p><a href={`tel:${phone}`}>{p.phone}</a></p>}{p.email && <p><a href={`mailto:${p.email}`}>{p.email}</a></p>}</div><div><h2>Students and management</h2><p>Access your existing account to view statements, messages and hostel records.</p><a className="secondary-button" href={p ? "/tenant/login" : "https://studentshostels.com/tenant/login"}>Student portal</a></div></section>}
 {!p && <section className="about-band"><div><h2>For landlords and landladies</h2><p>Manage your hostel through the StudentsHostels platform.</p></div><a className="secondary-button" href="https://systeminone.com/account">Open SYSTEM IN ONE</a></section>}
 <footer className="marketing-footer"><div><strong>{title}</strong><span>{p ? "Student accommodation · Your home near campus" : "Independent hostel websites"}</span></div><p>© {new Date().getFullYear()} {title}</p></footer></main>;
}
