import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowRightLeft, BedDouble, LogOut, Phone, ReceiptText, UserRound } from "lucide-react";
import { requireSession } from "@/lib/auth/session";
import { db } from "@/lib/db";

export default async function OccupancyDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const session = await requireSession(); const { id } = await params;
  const occupancy = await db.occupancy.findFirst({ where: { id, organizationId: session.organizationId }, include: { student: { include: { guardian: true } }, room: { include: { roomType: true } }, semester: true, charges: { include: { payments: { where: { reversedAt: null } } } } } });
  if (!occupancy) notFound();
  const canManage = session.role !== "CARETAKER" && occupancy.status === "ACTIVE";
  return <div><div className="page-heading-row"><div><p className="eyebrow">Occupancy record</p><h1>{occupancy.student.fullName}</h1><p>Room {occupancy.room.number} · {occupancy.semester.name}</p></div>{canManage ? <div className="heading-actions"><Link className="secondary-button no-underline" href={`/occupancy/${id}/transfer`}><ArrowRightLeft size={17} /> Transfer</Link><Link className="primary-button no-underline" href={`/occupancy/${id}/checkout`}><LogOut size={17} /> Check out</Link></div> : null}</div><section className="detail-grid"><article className="panel"><div className="panel-heading"><div><p className="panel-kicker">Student</p><h2>Contact and guardian</h2></div><UserRound size={19} /></div><dl className="detail-list"><div><dt>Phone</dt><dd><a href={`tel:${occupancy.student.phone}`}><Phone size={12} /> {occupancy.student.phone}</a></dd></div><div><dt>Admission number</dt><dd>{occupancy.student.admissionNumber || "Not provided"}</dd></div><div><dt>Guardian</dt><dd>{occupancy.student.guardian?.name || "Not provided"}</dd></div><div><dt>Guardian phone</dt><dd>{occupancy.student.guardian?.phone || "Not provided"}</dd></div></dl></article><article className="panel"><div className="panel-heading"><div><p className="panel-kicker">Accommodation</p><h2>Room and stay</h2></div><BedDouble size={19} /></div><dl className="detail-list"><div><dt>Room</dt><dd>Room {occupancy.room.number}</dd></div><div><dt>Type</dt><dd>{occupancy.room.roomType.name}</dd></div><div><dt>Check-in</dt><dd>{occupancy.checkInAt.toLocaleDateString("en-KE", { timeZone: "UTC" })}</dd></div><div><dt>Status</dt><dd>{occupancy.status}</dd></div></dl></article></section><section className="panel mt-5 overflow-hidden"><div className="panel-heading"><div><p className="panel-kicker">Financial position</p><h2>Charges and balances</h2></div><ReceiptText size={19} /></div><div className="table-scroll"><table className="data-table"><thead><tr><th>Description</th><th>Charge</th><th>Paid</th><th>Balance</th><th>Status</th></tr></thead><tbody>{occupancy.charges.map((charge) => { const paid = charge.payments.reduce((sum, item) => sum + Number(item.amount), 0); const balance = Math.max(0, Number(charge.amount) - paid); return <tr key={charge.id}><td><strong>{charge.description}</strong></td><td>KES {Number(charge.amount).toLocaleString("en-KE")}</td><td>KES {paid.toLocaleString("en-KE")}</td><td><strong>KES {balance.toLocaleString("en-KE")}</strong></td><td>{charge.status}</td></tr>; })}</tbody></table></div></section></div>;
}
