"use client";
import { FormSelect } from "@/components/form-select";
import Link from "next/link";
import { useActionState } from "react";
import { ArrowLeft, Save } from "lucide-react";
import { createAssetAction, updateAssetAction, type AssetFormState } from "@/app/(app)/assets/actions";
const initialState: AssetFormState = { error: "" };
type Option = { id: string; label: string }; type Defaults = { id: string; roomId: string; name: string; category: string; assetCode: string; quantity: number; condition: string; notes: string; active: boolean };
const categories = ["BED", "MATTRESS", "CHAIR", "TABLE", "CURTAIN", "KEY", "SOCKET", "LIGHT", "OTHER"]; const conditions = ["NEW", "GOOD", "FAIR", "DAMAGED", "MISSING", "NOT_APPLICABLE"];
export function AssetForm({ rooms, asset }: { rooms: Option[]; asset?: Defaults }) { const action = asset ? updateAssetAction.bind(null, asset.id) : createAssetAction; const [state, formAction, pending] = useActionState(action, initialState); return <form action={formAction} className="panel entity-form"><div className="form-section-heading"><div><p className="panel-kicker">Hostel inventory</p><h2>{asset ? "Edit asset" : "Add asset"}</h2></div></div><div className="form-grid"><label className="field-group"><span>Asset name *</span><input defaultValue={asset?.name} name="name" required /></label><label className="field-group"><span>Category *</span><FormSelect defaultValue={asset?.category ?? "OTHER"} name="category">{categories.map((value) => <option key={value} value={value}>{value}</option>)}</FormSelect></label><label className="field-group"><span>Room</span><FormSelect defaultValue={asset?.roomId ?? ""} name="roomId"><option value="">Shared/unallocated asset</option>{rooms.map((room) => <option key={room.id} value={room.id}>{room.label}</option>)}</FormSelect></label><label className="field-group"><span>Asset code</span><input defaultValue={asset?.assetCode} name="assetCode" /></label><label className="field-group"><span>Quantity *</span><input defaultValue={asset?.quantity ?? 1} min="1" name="quantity" type="number" required /></label><label className="field-group"><span>Condition *</span><FormSelect defaultValue={asset?.condition ?? "GOOD"} name="condition">{conditions.map((value) => <option key={value} value={value}>{value.replaceAll("_", " ")}</option>)}</FormSelect></label><label className="check-field"><input defaultChecked={asset?.active ?? true} name="active" type="checkbox" /><span>Asset is active</span></label><label className="field-group form-span-2"><span>Notes</span><textarea defaultValue={asset?.notes} name="notes" rows={3} /></label></div>{state.error ? <p className="form-error">{state.error}</p> : null}<div className="form-actions"><Link className="secondary-button no-underline" href="/assets"><ArrowLeft size={17} /> Cancel</Link><button className="primary-button" disabled={pending}><Save size={17} /> Save asset</button></div></form>; }
