"use client";

import Link from "next/link";
import { useActionState } from "react";
import { ArrowLeft, LogOut } from "lucide-react";
import { checkoutStudentAction, type StayFormState } from "@/app/(app)/occupancy/stay-actions";
const initialState: StayFormState = { error: "" };
type Item = { id: string; name: string; checkInCondition?: string; quantity?: number };
const conditions = ["NEW", "GOOD", "FAIR", "DAMAGED", "MISSING", "NOT_APPLICABLE"];
export function CheckoutInspectionForm({ occupancyId, allowOverride, propertyItems, assets }: { occupancyId: string; allowOverride: boolean; propertyItems: Item[]; assets: Item[] }) { const [state, action, pending] = useActionState(checkoutStudentAction.bind(null, occupancyId), initialState); const today = new Date().toISOString().slice(0, 10); return <form action={action} className="panel entity-form"><div className="form-section-heading"><div><p className="panel-kicker">Final clearance</p><h2>Checkout inspection</h2></div></div><div className="form-grid"><label className="field-group"><span>Checkout date *</span><input defaultValue={today} name="checkedOutAt" type="date" required /></label><label className="field-group form-span-2"><span>Overall room condition *</span><textarea minLength={3} name="checkoutCondition" rows={4} required /></label></div>{propertyItems.length ? <InspectionSection title="Student property" items={propertyItems} prefix="propertyCondition" /> : null}{assets.length ? <InspectionSection title="Hostel items in room" items={assets} prefix="assetCondition" /> : null}{allowOverride ? <div className="form-grid inspection-section"><label className="check-field form-span-2"><input name="overrideBalance" type="checkbox" /><span>Owner/Admin override: clear even if a balance remains</span></label><label className="field-group form-span-2"><span>Override reason</span><textarea minLength={8} name="overrideReason" rows={3} /></label></div> : null}{state.error ? <p className="form-error">{state.error}</p> : null}<div className="form-actions"><Link className="secondary-button no-underline" href={`/occupancy/${occupancyId}`}><ArrowLeft size={17} /> Cancel</Link><button className="primary-button" disabled={pending}><LogOut size={17} /> Complete checkout</button></div></form>; }
function InspectionSection({ title, items, prefix }: { title: string; items: Item[]; prefix: string }) { return <section className="inspection-section"><div className="form-divider"><p className="panel-kicker">Condition check</p><h3>{title}</h3></div><div className="inspection-list">{items.map((item) => <label className="inspection-row" key={item.id}><span><strong>{item.name}</strong><small>{item.quantity ? `Quantity ${item.quantity}` : `Check-in: ${item.checkInCondition}`}</small></span><select name={`${prefix}:${item.id}`} required><option value="">Select condition</option>{conditions.map((value) => <option key={value} value={value}>{value.replaceAll("_", " ")}</option>)}</select></label>)}</div></section>; }
