"use client";
import { useActionState, useState } from "react";
import { publishAction } from "@/app/(app)/communications/actions";
const templates={GENERAL:"",EXAM:"We wish you success in your examinations. Prepare well, rest sufficiently and respect quiet study hours. MMAMBUGUA HOSTEL management wishes you all the best.",HOLIDAY:"Please contact management before leaving for the holiday to confirm whether you are returning next semester or vacating, your room reservation and arrangements for your belongings.",BALANCE:"Please check your private account statement and clear outstanding rent arrears by the 10th. Contact management if you need assistance."};
export function CommunicationForm({students,requestId}:{students:Array<{id:string;fullName:string}>;requestId:string}) {
 const [state,action,pending]=useActionState(publishAction,{});
 const [audience,setAudience]=useState("ALL"),[body,setBody]=useState("");
 return <form action={action} className="panel entity-form"><h2>Post a tenant announcement</h2><input name="requestId" type="hidden" value={requestId}/><label className="field-group"><span>Subject</span><input name="title" required minLength={3} maxLength={160}/></label><label className="field-group"><span>Message type</span><select name="category" onChange={e=>setBody(templates[e.target.value as keyof typeof templates])}><option value="GENERAL">General notice</option><option value="EXAM">Examination wishes</option><option value="HOLIDAY">Holiday arrangements</option><option value="BALANCE">Payment notice</option></select></label><label className="field-group"><span>Message</span><textarea name="body" required minLength={10} maxLength={3000} rows={6} value={body} onChange={e=>setBody(e.target.value)}/></label><label className="field-group"><span>Audience</span><select name="audience" value={audience} onChange={e=>setAudience(e.target.value)}><option value="ALL">All current tenants</option><option value="SELECTED">Selected tenants</option></select></label>{audience==="SELECTED"?<fieldset><legend>Select recipients</legend><div style={{maxHeight:240,overflowY:"auto"}}>{students.map(s=><label className="check-field" key={s.id}><input name="studentIds" type="checkbox" value={s.id}/>{s.fullName}</label>)}</div></fieldset>:null}<label className="field-group"><span>Schedule (Nairobi time; leave blank to post now)</span><input name="publishAt" type="datetime-local"/></label><label className="check-field"><input name="whatsapp" type="checkbox"/>Prepare a WhatsApp copy for each tenant</label><p className="policy-note">Private inbox delivery is automatic at the chosen time. WhatsApp copies enter the manual send queue at the next daily run. Do not include an individual balance in an announcement to all tenants.</p>{state.error?<p className="form-error" role="alert">{state.error}</p>:null}{state.success?<p className="form-success" role="status">{state.success}</p>:null}<button className="primary-button" disabled={pending || !!state.success}>{pending?"Saving…":"Publish / schedule message"}</button>{state.success?<a className="secondary-button" href="/communications">Create another announcement</a>:null}</form>;
}
