"use client";

import { FormSelect } from "@/components/form-select";
import Link from "next/link";
import { useActionState } from "react";
import { ArrowLeft, Banknote, LoaderCircle, Plus } from "lucide-react";
import { createChargeAction, recordPaymentAction, type FinanceFormState } from "@/app/(app)/payments/actions";

const initialState: FinanceFormState = { error: "" };
type Option = { id: string; label: string };
type ChargeOption = Option & { balance: number };

export function ChargeForm({ students, semesters, roomTypes, selectedSemesterId }: { students: Option[]; semesters: Option[]; roomTypes: Option[]; selectedSemesterId?: string }) {
  const [state, action, pending] = useActionState(createChargeAction, initialState);
  return <form action={action} className="panel entity-form"><div className="form-section-heading"><div><p className="panel-kicker">Semester enrolment and receivable</p><h2>Add an existing student to a semester</h2><p>Select a previous or current student record. Do not create the student again.</p></div></div><div className="form-grid"><label className="field-group"><span>Student *</span><FormSelect name="studentId" required><option value="">Select existing student</option>{students.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</FormSelect></label><label className="field-group"><span>Charge type *</span><FormSelect defaultValue="SEMESTER_RENT" name="type"><option value="SEMESTER_RENT">Semester rent</option><option value="DAMAGE">Damage</option><option value="OTHER">Other</option></FormSelect></label><label className="field-group"><span>Semester</span><FormSelect defaultValue={selectedSemesterId ?? ""} name="semesterId"><option value="">Not semester-specific</option>{semesters.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</FormSelect></label><label className="field-group"><span>Accommodation type</span><FormSelect name="roomTypeId"><option value="">Not accommodation-specific</option>{roomTypes.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</FormSelect><small>Required for semester rent before room allocation.</small></label><label className="field-group"><span>Amount (KES) *</span><input min="1" name="amount" step="0.01" type="number" required /></label><label className="field-group"><span>Due date *</span><input name="dueDate" type="date" required /></label><label className="field-group form-span-2"><span>Description *</span><input maxLength={160} name="description" placeholder="e.g. September–December 2026 semester rent" required /></label></div>{state.error ? <p className="form-error" role="alert">{state.error}</p> : null}<div className="form-actions"><Link className="secondary-button no-underline" href="/payments"><ArrowLeft size={17} /> Cancel</Link><button className="primary-button" disabled={pending}>{pending ? <LoaderCircle className="animate-spin" size={17} /> : <Plus size={17} />} Add semester charge</button></div></form>;
}

export function PaymentForm({ charges, selectedChargeId, intake = false }: { charges: ChargeOption[]; selectedChargeId?: string; intake?: boolean }) {
  const [state, action, pending] = useActionState(recordPaymentAction, initialState);
  const today = new Date().toISOString().slice(0, 10);
  return <form action={action} className="panel entity-form"><div className="form-section-heading"><div><p className="panel-kicker">Collection</p><h2>{intake ? "Initial payment" : "Record payment"}</h2>{intake ? <p>A room can only be allocated after this payment is successfully recorded.</p> : null}</div></div><div className="form-grid"><label className="field-group form-span-2"><span>Outstanding charge *</span><FormSelect defaultValue={selectedChargeId ?? ""} name="chargeId" required><option value="">Select charge</option>{charges.map((item) => <option key={item.id} value={item.id}>{item.label} · Balance KES {item.balance.toLocaleString("en-KE")}</option>)}</FormSelect></label><label className="field-group"><span>Amount paid (KES) *</span><input min="1" name="amount" step="0.01" type="number" required /></label><label className="field-group"><span>Payment date *</span><input defaultValue={today} name="paidAt" type="date" required /></label><label className="field-group"><span>Payment method *</span><FormSelect defaultValue="MPESA" name="method"><option value="MPESA">M-Pesa</option><option value="BANK_TRANSFER">Bank transfer</option><option value="CASH">Cash</option><option value="CARD">Card</option><option value="OTHER">Other</option></FormSelect></label><label className="field-group"><span>M-Pesa / reference number</span><input maxLength={100} name="reference" placeholder="Required for electronic payments" /></label><label className="field-group"><span>Next balance due date</span><input name="nextBalanceDueDate" type="date" /><small>Use when this is a partial payment.</small></label><label className="field-group form-span-2"><span>Notes</span><textarea maxLength={500} name="notes" rows={3} /></label></div>{state.error ? <p className="form-error" role="alert">{state.error}</p> : null}<div className="form-actions"><Link className="secondary-button no-underline" href="/payments"><ArrowLeft size={17} /> Cancel</Link><button className="primary-button" disabled={pending}>{pending ? <LoaderCircle className="animate-spin" size={17} /> : <Banknote size={17} />} {intake ? "Save payment and allocate room" : "Save and open receipt"}</button></div></form>;
}
