"use client";
import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import type { ResidentAlertSummary } from "@/lib/resident-alerts";
import styles from "./resident-services.module.css";
export function ResidentAlertPanel({ tenant = false }: { tenant?: boolean }) {
  const [data, setData] = useState<ResidentAlertSummary | null>(null), [error, setError] = useState("");
  const refresh = useCallback(async (signal?: AbortSignal) => {
    try { const response = await fetch(`/api/resident-alerts?audience=${tenant ? "tenant" : "staff"}`, { cache: "no-store", signal }); const result = await response.json(); if (!response.ok) throw Error(result.error || "Live alerts unavailable."); setData(result); setError(""); }
    catch (e) { if (!(e instanceof Error && e.name === "AbortError")) { setData(null); setError(e instanceof Error ? e.message : "Live alerts unavailable."); } }
  }, [tenant]);
  useEffect(() => { const controller = new AbortController(); const first = setTimeout(() => void refresh(controller.signal), 0); const timer = setInterval(() => { if (!document.hidden) void refresh(controller.signal); }, 60000); return () => { controller.abort(); clearTimeout(first); clearInterval(timer); }; }, [refresh]);
  return <section className={`panel ${styles.card}`} aria-label="Live resident alerts"><h2>Attention needed</h2><p className={styles.meta}>Checks current records every minute while this page is visible. A missing check-out record requires staff follow-up; it is not proof someone is still inside.</p>{error ? <p role="alert" className="form-error">{error}</p> : data ? <><div className={styles.actions}><Link href={tenant ? "/tenant/visitors" : "/visitors?filter=OVERDUE"} className={data.overdueCount ? styles.warning : styles.notice}><strong>{data.overdueCount}</strong> check-out overdue</Link><Link href={tenant ? "/tenant/visitors" : "/visitors"} className={styles.notice}><strong>{data.pendingVisits}</strong> visitor requests</Link>{data.awaitingManagement !== null && <Link className={styles.notice} href="/communications/inbox"><strong>{data.awaitingManagement}</strong> conversations awaiting management</Link>}{data.pendingRegistrations !== null && <Link className={styles.notice} href="/students/registrations"><strong>{data.pendingRegistrations}</strong> registrations to verify</Link>}{data.unreadMessages !== null && <Link className={styles.notice} href="/tenant/messages"><strong>{data.unreadMessages}</strong> unread notices</Link>}</div>{data.overdue.map(v => <article key={v.id} className={styles.warning}><strong>{v.visitorName}</strong> · host: {v.host} · room {v.room}<p>Expected departure: {new Date(v.expectedDeparture).toLocaleString("en-GB", { timeZone: v.timeZone })} ({v.timeZone}). Check-out has not been recorded.</p></article>)}{data.overdueCount > 10 && <p>Showing the oldest 10 overdue records. Open the visitor register for the complete list.</p>}<p className={styles.meta}>Last checked: {new Date(data.observedAt).toLocaleTimeString()}</p></> : <p>Loading current records…</p>}<button type="button" className="secondary-button" onClick={() => void refresh()}>Refresh alerts</button></section>;
}
