"use client";
import Image from "next/image";
import { upload } from "@vercel/blob/client";
import { Camera, LoaderCircle, X } from "lucide-react";
import { useState } from "react";

type Kind="inside"|"outside"|"compound";
type Value={url:string;pathname?:string};
const labels:Record<Kind,{title:string;hint:string}>={inside:{title:"Inside room",hint:"Show the room interior clearly"},outside:{title:"Outside room",hint:"Show the entrance/door"},compound:{title:"Compound / block",hint:"Show the surrounding block or compound"}};
export function RoomPhotoUploader({defaults={}}:{defaults?:Partial<Record<Kind,Value>>}){const [photos,setPhotos]=useState(defaults);const [busy,setBusy]=useState<Kind|null>(null);async function pick(kind:Kind,file?:File){if(!file)return;setBusy(kind);try{const blob=await upload(`rooms/${kind}/${file.name}`,file,{access:"public",handleUploadUrl:"/api/room-photos/upload"});setPhotos(v=>({...v,[kind]:{url:blob.url,pathname:blob.pathname}}));}finally{setBusy(null)}}return <div className="form-span-2"><div className="form-section-heading"><div><p className="panel-kicker">Room photography</p><h2>Room photos</h2></div><p>Up to three photos: inside, outside and compound/block.</p></div><div className="room-photo-grid">{(["inside","outside","compound"] as Kind[]).map(kind=>{const photo=photos[kind];return <div className="room-photo-slot" key={kind}><strong>{labels[kind].title}</strong><small>{labels[kind].hint}</small>{photo?<div className="room-photo-preview"><Image src={photo.url} alt={labels[kind].title} fill sizes="(max-width: 700px) 100vw, 33vw" unoptimized/><button type="button" className="room-photo-remove" onClick={()=>setPhotos(v=>({...v,[kind]:undefined}))} aria-label={`Remove ${labels[kind].title}`}><X size={16}/></button></div>:<label className="room-photo-pick">{busy===kind?<LoaderCircle className="animate-spin" size={24}/>:<Camera size={24}/>}<span>{busy===kind?"Uploading…":"Upload photo"}</span><input type="file" accept="image/jpeg,image/png,image/webp" capture="environment" disabled={busy!==null} onChange={e=>void pick(kind,e.target.files?.[0])}/></label>}<input type="hidden" name={`${kind}PhotoUrl`} value={photo?.url??""}/><input type="hidden" name={`${kind}PhotoPathname`} value={photo?.pathname??""}/></div>})}</div><p className="muted-note mt-3">JPG, PNG or WebP · maximum 12 MB each. Photos remain attached to this room record.</p></div>}
