"use client";
import { useActionState, useState } from "react";
import { requestVisitAction, gateVisitAction, cancelVisitAction } from "@/app/tenant/visitors/actions";
import styles from "./resident-services.module.css";
function Result({ state }: { state: { error?: string; success?: string } }) { return <>{state.error && <p role="alert" className="form-error">{state.error}</p>}{state.success && <p role="status" className="form-success">{state.success}</p>}</>; }
export function VisitorRequestForm({ requestId, rooms }: { requestId: string; rooms: Array<{ id: string; label: string; timeZone: string }> }) {
  const [state, action, pending] = useActionState(requestVisitAction, {});
  const [roomId, setRoomId] = useState(rooms[0]?.id ?? "");
  return <form action={action}><input type="hidden" name="requestId" value={requestId}/><label className="field-group"><span>My room</span><select name="occupancyId" required value={roomId} onChange={e=>setRoomId(e.target.value)}>{rooms.map(r => <option key={r.id} value={r.id}>{r.label}</option>)}</select></label><p className={styles.notice}>Enter arrival and departure in <strong>{rooms.find(r=>r.id===roomId)?.timeZone ?? "the hostel time zone"}</strong>.</p><div className={styles.grid}><label className="field-group"><span>Visitor full name</span><input name="visitorName" required minLength={2} maxLength={120}/></label><label className="field-group"><span>Visitor phone (with country code)</span><input name="visitorPhone" type="tel" required maxLength={30}/></label><label className="field-group"><span>Expected arrival — hostel time</span><input name="arrival" type="datetime-local" required/></label><label className="field-group"><span>Expected departure — hostel time</span><input name="departure" type="datetime-local" required/></label><label className="field-group"><span>Relationship / purpose of visit</span><input name="purpose" required minLength={2} maxLength={200}/></label><label className="field-group"><span>Vehicle registration (optional)</span><input name="vehicle" maxLength={30}/></label></div><p className={styles.meta}>Share only the details needed for the visit and let your visitor know the hostel will record arrival and departure. A request does not authorize entry.</p><Result state={state}/><button className="primary-button" disabled={pending || !!state.success}>{pending ? "Saving…" : "Submit visitor request"}</button>{state.success && <a href="/tenant/visitors">Start another request</a>}</form>;
}
export function VisitorActionForm({ id, status, tenant = false }: { id: string; status: string; tenant?: boolean }) {
  const [state, action, pending] = useActionState(tenant ? cancelVisitAction : gateVisitAction, {});
  if (!["REQUESTED", "APPROVED", "CHECKED_IN"].includes(status) || (tenant && status === "CHECKED_IN")) return null;
  return <form action={action}><input type="hidden" name="id" value={id}/>{!tenant && <><label className="check-field"><input type="checkbox" name="verified"/><span>{status === "CHECKED_IN" ? "I personally verified the visitor has left." : "I verified the visitor's identity and host. For check-in, I confirm arrival at the gate."}</span></label><label className="field-group"><span>Verification note (optional; visible to the host)</span><input name="note" maxLength={300} placeholder="Do not record full identity document numbers"/></label></>}<Result state={state}/><div className={styles.actions}>{tenant ? <button className="secondary-button" disabled={pending || !!state.success}>Cancel visit</button> : status === "CHECKED_IN" ? <button name="decision" value="CHECK_OUT" className="primary-button" disabled={pending || !!state.success}>Verify check-out</button> : <>{status === "REQUESTED" && <button name="decision" value="APPROVE" className="secondary-button" disabled={pending || !!state.success}>Approve expected visit</button>}<button name="decision" value="CHECK_IN" className="primary-button" disabled={pending || !!state.success}>Verify check-in</button><button name="decision" value="DENY" className="secondary-button" disabled={pending || !!state.success}>Decline visit</button></>}</div></form>;
}
