import test from 'node:test';
import assert from 'node:assert/strict';
import type {PrismaClient} from '../src/generated/prisma/client';
import {createConversation,replyConversation} from '../src/lib/tenant-conversations';
import {emailResult,sendCommunicationEmails} from '../src/lib/communication-email';
const student={studentId:'one',organizationId:'hostel',name:'One'},manager={userId:'owner',organizationId:'hostel',name:'Owner',role:'OWNER' as const};
const request={subject:'Water request',body:'Please check the water supply.',category:'MAINTENANCE',requestId:'de2d264f-7a52-478b-9bca-ab261c88cce8'};
function contactFixture(eligible=true,allowed=true,conversation=true){
 let entries=0,created=0;const notices:unknown[]=[],audits:unknown[]=[];let scope:unknown;
 const tx={$queryRaw:async()=>[],student:{findFirst:async()=>eligible?{id:'one'}:null},tenantConversationEntry:{findUnique:async()=>null,count:async()=>0,create:async()=>{entries++;return{id:'entry'}}},tenantConversation:{create:async()=>{created++;return{id:'thread'}},findFirst:async(args:{where:unknown})=>{scope=args.where;return conversation?{id:'thread',organizationId:'hostel',studentId:'one',subject:'Water request'}:null},update:async()=>({})},communicationSettings:{findUnique:async()=>({emailCopies:false})},tenantMessage:{create:async(args:unknown)=>{notices.push(args)}},auditLog:{create:async(args:unknown)=>{audits.push(args)}}};
 const db={...tx,user:{findFirst:async()=>allowed?{id:'owner'}:null},$transaction:async(fn:(x:unknown)=>unknown)=>fn(tx)} as unknown as PrismaClient;
 return{db,notices,audits,get entries(){return entries},get created(){return created},get scope(){return scope}};
}
test('anonymous student cannot start a conversation',async()=>{const f=contactFixture();assert.ok((await createConversation(f.db,null,request)).error);assert.equal(f.created,0)});
test('disabled or former tenant cannot post',async()=>{const f=contactFixture(false);assert.ok((await createConversation(f.db,student,request)).error);assert.equal(f.created,0)});
test('eligible tenant creates a private audited thread',async()=>{const f=contactFixture();assert.ok('success' in await createConversation(f.db,student,request));assert.equal(f.created,1);assert.equal(f.audits.length,1);assert.equal(f.notices.length,0)});
test('student reply scopes conversation to own identity and hostel',async()=>{const f=contactFixture(true,true,false);assert.ok((await replyConversation(f.db,student,{conversationId:'foreign-thread',body:'Private reply',requestId:request.requestId},false)).error);assert.deepEqual(f.scope,{id:'foreign-thread',organizationId:'hostel',studentId:'one'});assert.equal(f.entries,0)});
test('unauthorized manager cannot reply',async()=>{const f=contactFixture(true,false);assert.ok((await replyConversation(f.db,manager,{conversationId:'thread',body:'A reply',requestId:request.requestId},true)).error);assert.equal(f.entries,0)});
test('management reply adds a private notification without sensitive reply text',async()=>{const f=contactFixture();await replyConversation(f.db,manager,{conversationId:'thread',body:'Private financial details here',requestId:request.requestId},true);assert.equal(f.entries,1);assert.equal(f.notices.length,1);assert.doesNotMatch(JSON.stringify(f.notices),/Private financial details/);assert.equal(f.audits.length,1)});
test('email result distinguishes acceptance, definite failure and uncertainty',()=>{assert.equal(emailResult(200,'provider-id').status,'PROVIDER_ACCEPTED');assert.equal(emailResult(200).status,'REVIEW');assert.equal(emailResult(500).status,'REVIEW');assert.equal(emailResult(429).status,'RETRY');assert.equal(emailResult(422).status,'FAILED')});
function emailFixture(email:string|null='student@example.invalid'){
 const row={id:'notice',organizationId:'hostel',studentId:'one',title:'Private notice',body:'Your hostel message',emailStatus:'QUEUED',emailAttempts:0,emailGeneration:0,emailRecipient:null,emailFrom:null};
 const tx={$queryRaw:async()=>[],student:{findFirst:async()=>({email})},tenantMessage:{findUnique:async()=>({...row}),findMany:async()=>['QUEUED','RETRY'].includes(row.emailStatus)?[{id:row.id}]:[],update:async({data}:{data:Record<string,unknown>})=>{for(const [key,value]of Object.entries(data)){if(key==='emailAttempts')row.emailAttempts++;else Object.assign(row,{[key]:value})}return{...row}}}};
 return{row,db:{...tx,$transaction:async(fn:(x:unknown)=>unknown)=>fn(tx)} as unknown as PrismaClient};
}
test('email targets one recipient with stable key and does not resend accepted mail',async()=>{const f=emailFixture();let sent=0;const sender=(async(_url:unknown,options:RequestInit)=>{sent++;assert.match(JSON.stringify(options.headers),/hostel-notice\/notice\/0/);assert.deepEqual(JSON.parse(options.body as string).to,['student@example.invalid']);return new Response(JSON.stringify({id:'provider-id'}),{status:200})}) as typeof fetch;const config={apiKey:'FAKE',from:'hostel@example.invalid'};await sendCommunicationEmails(f.db,new Date(),sender,config);await sendCommunicationEmails(f.db,new Date(),sender,config);assert.equal(sent,1);assert.equal(f.row.emailStatus,'PROVIDER_ACCEPTED')});
test('missing email never calls provider and is visible as a failure',async()=>{const f=emailFixture(null);let sent=0;const sender=(async()=>{sent++;return new Response()}) as typeof fetch;await sendCommunicationEmails(f.db,new Date(),sender,{apiKey:'FAKE',from:'hostel@example.invalid'});assert.equal(sent,0);assert.equal(f.row.emailStatus,'MISSING_EMAIL')});
test('uncertain provider response is not automatically retried',async()=>{const f=emailFixture();let sent=0;const sender=(async()=>{sent++;throw Error('timeout')}) as typeof fetch;const config={apiKey:'FAKE',from:'hostel@example.invalid'};await sendCommunicationEmails(f.db,new Date(),sender,config);await sendCommunicationEmails(f.db,new Date(),sender,config);assert.equal(sent,1);assert.equal(f.row.emailStatus,'REVIEW')});
