import test from 'node:test';
import assert from 'node:assert/strict';
import type {PrismaClient} from '../src/generated/prisma/client';
import {invitationToken,invitationHash,usableInvitation,activateInvitation,inviteCandidateWhere,invitationManager} from '../src/lib/portal-invitations';
const secret='FAKE-INVITATION-SECRET-FOR-TESTS-ONLY';
const base={id:'a2516265-5d31-4d10-9737-38c0f4f3c5fd',generation:0,recipient:'one@example.invalid',expiresAt:new Date(Date.now()+72*3600000)};
function fixture(eligible=true){
 const row={...base,organizationId:'hostel',studentId:'one',tokenHash:invitationHash(invitationToken(base,secret)),usedAt:null as Date|null,status:'PROVIDER_ACCEPTED'};let writes=0;const audits:unknown[]=[],locks:unknown[]=[];
 const tx={tenantPortalInvitation:{findUnique:async(args:{where:{tokenHash?:string}})=>args.where.tokenHash===row.tokenHash?{...row}:null,update:async({data}:{data:Record<string,unknown>})=>{Object.assign(row,data);return row}},student:{findFirst:async()=>eligible?{id:'one',email:'one@example.invalid'}:null,updateMany:async({data}:{data:Record<string,unknown>})=>{assert.equal(data.portalEnabled,true);assert.notEqual(data.portalPasswordHash,'NewPasswordForTests');writes++;return{count:1}}},$queryRaw:async(...args:unknown[])=>{locks.push(args);return[]},auditLog:{create:async(a:unknown)=>{audits.push(a)}}};
 const db={...tx,$transaction:async(fn:(tx:unknown)=>unknown)=>fn(tx)} as unknown as PrismaClient;
 return {row,db,audits,locks,get writes(){return writes}};
}
test('invitation token is stable and changes for recipient, generation and expiry',()=>{const token=invitationToken(base,secret);assert.equal(token,invitationToken(base,secret));assert.notEqual(token,invitationToken({...base,generation:1},secret));assert.notEqual(token,invitationToken({...base,recipient:'two@example.invalid'},secret));assert.notEqual(token,invitationToken({...base,expiresAt:new Date(base.expiresAt.getTime()+1)},secret));assert.equal(invitationHash(token).length,64)});
test('malformed and tampered invitation cannot be used',async()=>{const f=fixture();assert.equal(await usableInvitation(f.db,'invalid'),null);assert.equal(await usableInvitation(f.db,invitationToken(base,secret).slice(0,-1)+(invitationToken(base,secret).endsWith('x')?'y':'x')),null);assert.equal(f.writes,0)});
test('expired or consumed invitation is unavailable',async()=>{const f=fixture();const token=invitationToken(base,secret);assert.equal(await usableInvitation(f.db,token,new Date(base.expiresAt.getTime()+1)),null);f.row.usedAt=new Date();assert.equal(await usableInvitation(f.db,token),null)});
test('disabled or ineligible account cannot use an invitation',async()=>{const f=fixture(false);assert.equal(await usableInvitation(f.db,invitationToken(base,secret)),null)});
test('mismatched passwords cannot activate an account',async()=>{const f=fixture();assert.ok((await activateInvitation(f.db,{token:invitationToken(base,secret),password:'NewPasswordForTests',confirmation:'DifferentPassword'})).error);assert.equal(f.writes,0)});
test('activation locks account and invitation, hashes password and consumes link once',async()=>{const f=fixture();const input={token:invitationToken(base,secret),password:'NewPasswordForTests',confirmation:'NewPasswordForTests'};assert.ok('success' in await activateInvitation(f.db,input));assert.equal(f.writes,1);assert.equal(f.locks.length,2);assert.equal(f.audits.length,1);assert.equal(f.row.status,'ACTIVATED');assert.equal(f.row.tokenHash,null);assert.ok((await activateInvitation(f.db,input)).error);assert.equal(f.writes,1)});
test('automatic candidates exclude activated, previously used and blocked portals',()=>{const where=inviteCandidateWhere('hostel');assert.equal(where.organizationId,'hostel');assert.equal(where.portalEnabled,false);assert.equal(where.portalPasswordHash,null);assert.equal(where.portalLastLoginAt,null);assert.equal(where.portalInviteBlocked,false);assert.deepEqual(where.organization,{status:'ACTIVE'})});
test('only current active owners and admins can control account invitations',async()=>{let scope:unknown;const db={user:{findFirst:async(args:{where:unknown})=>{scope=args.where;return null}}} as unknown as PrismaClient;assert.equal(await invitationManager(db,null),null);await invitationManager(db,{userId:'owner',organizationId:'hostel',role:'OWNER',name:'Owner'});assert.deepEqual(scope,{id:'owner',organizationId:'hostel',active:true,role:{in:['OWNER','ADMIN']}})});
