import test from "node:test";
import assert from "node:assert/strict";
import type { PrismaClient } from "../src/generated/prisma/client";
import { createBookingTicket,verifyBookingTicket,validMoveInDate,submitBooking,bookingOptions,updateBooking } from "../src/lib/booking-requests";
process.env.SESSION_SECRET="isolated-booking-test-secret-2026";
const now=new Date("2026-10-08T12:00:00Z"),property={id:"p1",organizationId:"org1"};
const raw={fullName:"Test Student",phone:"0712345678",email:"TEST@example.invalid",roomTypeId:"type1",preferredMoveIn:"2026-10-10",consent:true};
function fixture(){
 const records:Record<string,unknown>[]=[];const events:unknown[]=[];let available=true,prior:unknown=null,contactCount=0,propertyCount=0,user:unknown={id:"u1",sessionVersion:0},parent=true;
 const tx={$queryRaw:async()=>[],property:{findFirst:async()=>parent?property:null},bookingRequest:{findUnique:async()=>prior,count:async({where}:{where:{contactKey?:string}})=>where.contactKey?contactCount:propertyCount,create:async({data}:{data:Record<string,unknown>})=>{records.push(data);return data;},updateMany:async(args:unknown)=>{events.push(args);return{count:1};}},room:{findMany:async()=>available?[{id:"r1",status:"VACANT",capacityOverride:null,roomType:{id:"type1",name:"Single",monthlyRate:4500,semesterRate:18000,defaultCapacity:1},occupancies:[],breakReservations:[]}]:[]},user:{findFirst:async()=>user},auditLog:{create:async(args:unknown)=>events.push(args)}};
 const db={...tx,$transaction:async(fn:(t:unknown)=>unknown)=>fn(tx)} as unknown as PrismaClient;
 return{db,records,events,setAvailable:(v:boolean)=>available=v,setPrior:(v:unknown)=>prior=v,setCounts:(c:number,p:number)=>{contactCount=c;propertyCount=p;},setUser:(v:unknown)=>user=v,setParent:(v:boolean)=>parent=v};
}
test("booking tickets bind property, resist tampering and expire",()=>{const ticket=createBookingTicket("p1",now);assert.ok(verifyBookingTicket(ticket,"p1",now));assert.equal(verifyBookingTicket(ticket,"p2",now),null);assert.equal(verifyBookingTicket(ticket+"x","p1",now),null);assert.equal(verifyBookingTicket(ticket,"p1",new Date(now.getTime()+31*60000)),null);assert.equal(verifyBookingTicket(ticket,"p1",new Date(now.getTime()-2*60000)),null);});
test("move-in date is calendar-valid, current in Nairobi and within one year",()=>{assert.equal(validMoveInDate("2026-10-08",now),true);assert.equal(validMoveInDate("2026-10-07",now),false);assert.equal(validMoveInDate("2027-02-30",now),false);assert.equal(validMoveInDate("2028-01-01",now),false);assert.equal(validMoveInDate("2026-10-08",new Date("2026-10-08T22:00:00Z")),false);});
test("valid request persists only scoped contact data and produces a reference",async()=>{const f=fixture();const result=await submitBooking(f.db,property,raw,createBookingTicket("p1",now),now);assert.match(result.reference!,/^BR-[A-F0-9]{16}$/);assert.equal(f.records.length,1);assert.equal(f.records[0].organizationId,"org1");assert.equal(f.records[0].email,"test@example.invalid");assert.equal(f.records[0].status,undefined);assert.notEqual(f.records[0].contactKey,raw.phone);});
test("missing consent, forged ticket, foreign room type and stale availability make no request",async()=>{for(const input of [{...raw,consent:false},{...raw,roomTypeId:"foreign"},{...raw,preferredMoveIn:"2026-02-30"}]){const f=fixture();assert.ok((await submitBooking(f.db,property,input,createBookingTicket("p1",now),now)).error);assert.equal(f.records.length,0);}const f=fixture();assert.ok((await submitBooking(f.db,property,raw,createBookingTicket("other",now),now)).error);f.setAvailable(false);assert.ok((await submitBooking(f.db,property,raw,createBookingTicket("p1",now),now)).error);assert.equal(f.records.length,0);});
test("unpublished property blocks submissions",async()=>{const f=fixture();f.setParent(false);assert.ok((await submitBooking(f.db,property,raw,createBookingTicket("p1",now),now)).error);assert.equal(f.records.length,0);});
test("phone and property limits block further persistence",async()=>{for(const limits of [[3,0],[0,100]]){const f=fixture();f.setCounts(...limits as [number,number]);assert.ok((await submitBooking(f.db,property,raw,createBookingTicket("p1",now),now)).error);assert.equal(f.records.length,0);}});
test("same signed request returns its receipt; altered input cannot reuse it",async()=>{const f=fixture();const ticket=createBookingTicket("p1",now);f.setPrior({...raw,email:"test@example.invalid",preferredMoveIn:new Date("2026-10-10"),reference:"BR-EXISTING"});assert.equal((await submitBooking(f.db,property,raw,ticket,now)).reference,"BR-EXISTING");assert.ok((await submitBooking(f.db,property,{...raw,phone:"0799999999"},ticket,now)).error);assert.equal(f.records.length,0);});
test("reserved occupants, break holds and maintenance rooms are not offered",async()=>{const rooms=[{status:"VACANT",capacityOverride:null,roomType:{id:"type1",name:"Single",monthlyRate:4500,semesterRate:18000,defaultCapacity:1},occupancies:[{studentId:"reserved"}],breakReservations:[]},{status:"MAINTENANCE",capacityOverride:null,roomType:{id:"type2",defaultCapacity:2},occupancies:[],breakReservations:[]}];const db={room:{findMany:async(args:unknown)=>{assert.ok(JSON.stringify(args).includes("RESERVED"));return rooms;}}} as unknown as PrismaClient;assert.deepEqual(await bookingOptions(db,"p1","org1"),[]);});
test("management mutation scopes request to session organization and audits no contact data",async()=>{const f=fixture();assert.deepEqual(await updateBooking(f.db,{userId:"u1",organizationId:"org1",name:"Owner",role:"OWNER",sessionVersion:0},"request1","CONTACTED"),{});assert.deepEqual(f.events[0],{where:{id:"request1",organizationId:"org1"},data:{status:"CONTACTED"}});assert.ok(!JSON.stringify(f.events[1]).includes(raw.phone));});
test("revoked or inactive managers and unsupported paid status cannot update",async()=>{const session={userId:"u1",organizationId:"org1",name:"Owner",role:"OWNER" as const,sessionVersion:0};for(const user of [null,{id:"u1",sessionVersion:1}]){const f=fixture();f.setUser(user);assert.ok((await updateBooking(f.db,session,"request1","CONTACTED")).error);assert.equal(f.events.length,0);}const f=fixture();assert.ok((await updateBooking(f.db,session,"request1","PAID")).error);assert.equal(f.events.length,0);});
