import Link from "next/link";
import { ArrowLeft, CheckCircle2, CircleAlert, Link2, SearchX } from "lucide-react";
import { ignoreMpesaTransactionAction, matchMpesaPaymentAction } from "./actions";
import { MpesaImportForm } from "@/components/mpesa-import-form";
import { requireSession } from "@/lib/auth/session";
import { db } from "@/lib/db";

const money = (value: number) => `KES ${value.toLocaleString("en-KE", { maximumFractionDigits: 2 })}`;
const labels: Record<string, string> = { UNMATCHED: "Unmatched", MATCHED: "Matched", AMOUNT_MISMATCH: "Amount mismatch", REVERSED: "Reversed", IGNORED: "Ignored" };

export default async function ReconciliationPage({ searchParams }: { searchParams: Promise<{ error?: string; matched?: string }> }) {
  const session = await requireSession();
  if (session.role === "CARETAKER") return <div className="inline-empty"><SearchX size={28} /><strong>Access restricted</strong><p>Ask the Owner, Admin or Manager to reconcile payments.</p></div>;
  const query = await searchParams;
  const [transactions, payments] = await Promise.all([
    db.mpesaTransaction.findMany({ where: { organizationId: session.organizationId }, include: { payment: { include: { student: true } } }, orderBy: { transactedAt: "desc" }, take: 100 }),
    db.payment.findMany({ where: { organizationId: session.organizationId, method: "MPESA", reversedAt: null, mpesaTransaction: null }, include: { student: true }, orderBy: { paidAt: "desc" }, take: 100 }),
  ]);
  const counts = Object.fromEntries(["MATCHED", "UNMATCHED", "AMOUNT_MISMATCH", "REVERSED"].map((status) => [status, transactions.filter((item) => item.status === status).length]));
  return <div><div className="page-heading-row"><div><p className="eyebrow">Finance control</p><h1>M-Pesa reconciliation</h1><p>Compare provider statement entries against recorded hostel payments.</p></div><Link className="secondary-button no-underline" href="/payments"><ArrowLeft size={17} /> Payments</Link></div>
    <section className="room-summary-grid"><article className="compact-stat"><span className="metric-icon metric-green"><CheckCircle2 size={22} /></span><div><p>Matched</p><strong>{counts.MATCHED}</strong></div></article><article className="compact-stat"><span className="metric-icon metric-blue"><Link2 size={22} /></span><div><p>Unmatched</p><strong>{counts.UNMATCHED}</strong></div></article><article className="compact-stat"><span className="metric-icon metric-red"><CircleAlert size={22} /></span><div><p>Amount mismatch</p><strong>{counts.AMOUNT_MISMATCH}</strong></div></article><article className="compact-stat"><span className="metric-icon metric-violet"><SearchX size={22} /></span><div><p>Reversed</p><strong>{counts.REVERSED}</strong></div></article></section>
    <div className="mt-5"><MpesaImportForm /></div>{query.error ? <p className="form-error standalone-alert" role="alert">{query.error}</p> : null}{query.matched ? <p className="form-success standalone-alert">Transaction matched successfully.</p> : null}
    <section className="panel mt-5 overflow-hidden"><div className="panel-heading"><div><p className="panel-kicker">Last 100 entries</p><h2>Statement transactions</h2></div></div>{transactions.length ? <div className="table-scroll"><table className="data-table reconciliation-table"><thead><tr><th>Transaction</th><th>Phone / account</th><th>Amount</th><th>Date</th><th>Status</th><th>Matched receipt</th><th>Resolve</th></tr></thead><tbody>{transactions.map((item) => <tr key={item.id}><td><strong>{item.transactionCode}</strong></td><td>{item.phone || "—"}<small className="table-subtext">{item.reference || "No account reference"}</small></td><td>{money(Number(item.amount))}</td><td>{item.transactedAt.toLocaleString("en-KE", { timeZone: "Africa/Nairobi" })}</td><td><span className={`status-pill reconciliation-${item.status.toLowerCase()}`}>{labels[item.status]}</span>{item.notes ? <small className="table-subtext">{item.notes}</small> : null}</td><td>{item.payment ? <Link className="table-action" href={`/payments/${item.payment.id}/receipt`}>{item.payment.receiptNumber}<small className="table-subtext">{item.payment.student.fullName}</small></Link> : "—"}</td><td>{!item.paymentId && !["IGNORED", "REVERSED"].includes(item.status) ? <div className="reconciliation-actions"><form action={matchMpesaPaymentAction}><input name="transactionId" type="hidden" value={item.id} /><select aria-label={`Payment for ${item.transactionCode}`} name="paymentId" required><option value="">Select payment</option>{payments.filter((payment) => Number(payment.amount) === Number(item.amount)).map((payment) => <option key={payment.id} value={payment.id}>{payment.receiptNumber} · {payment.student.fullName} · {money(Number(payment.amount))}</option>)}</select><button className="table-action" type="submit">Match</button></form><form action={ignoreMpesaTransactionAction}><input name="transactionId" type="hidden" value={item.id} /><button className="muted-action" type="submit">Ignore</button></form></div> : "—"}</td></tr>)}</tbody></table></div> : <div className="inline-empty"><SearchX size={25} /><strong>No M-Pesa transactions imported</strong><p>Upload a CSV statement to begin reconciliation.</p></div>}</section>
  </div>;
}
