import { getSession } from "@/lib/auth/session";
import { getTenantSession } from "@/lib/auth/tenant-session";
import { db } from "@/lib/db";
import { sameOrigin,serviceId } from "@/lib/service-security";
import { messagingProperties,messagingCountry } from "@/lib/whatsapp-communications";
import { whatsappNumber } from "@/lib/whatsapp-policy";
const headers={"Cache-Control":"private, no-store"};
async function principal(request:Request){const tenant=new URL(request.url).searchParams.get("audience")==="tenant";const s=tenant?await getTenantSession():await getSession();return s?{organizationId:s.organizationId,accountId:"studentId" in s?s.studentId:s.userId,audience:tenant?"tenant":"staff"}:null;}
export async function GET(request:Request){const p=await principal(request);if(!p)return Response.json({error:"Sign in first."},{status:401,headers});const consent=await db.whatsAppConsent.findUnique({where:{organizationId_accountId_audience:p}});return Response.json({enabled:consent?.enabled??false},{headers});}
export async function POST(request:Request){if(!sameOrigin(request))return Response.json({error:"Request not allowed."},{status:403,headers});const p=await principal(request);if(!p)return Response.json({error:"Sign in first."},{status:401,headers});const body=await request.json().catch(()=>null);if(typeof body?.enabled!=="boolean")return Response.json({error:"Choose your notification preference."},{status:400,headers});const record=p.audience==="tenant"?await db.student.findFirst({where:{id:p.accountId,organizationId:p.organizationId},select:{phone:true}}):await db.user.findFirst({where:{id:p.accountId,organizationId:p.organizationId},select:{phone:true}});const properties=await messagingProperties(db,p.organizationId),phone=whatsappNumber(record?.phone,messagingCountry(properties,p.organizationId));if(!phone&&body.enabled)return Response.json({error:"Ask management to update your international phone number first."},{status:400,headers});await db.whatsAppConsent.upsert({where:{organizationId_accountId_audience:p},create:{id:serviceId(...Object.values(p)),...p,phone:phone??"",enabled:body.enabled,consentText:"I agree to receive hostel messages, reminders, invitations and receipt links on WhatsApp at my registered phone number. I can turn this off at any time."},update:{phone:phone??"",enabled:body.enabled}});return Response.json({enabled:body.enabled},{headers});}
